// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package v1

import (
	"context"
	i4db02de4fa95db6167263a0a43a6a58c23904074eb83cc381a94eba9021abdb2 "github.com/cedana/cedana-go-sdk/models"
	i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f "github.com/microsoft/kiota-abstractions-go"
)

// InferenceProfilesItemRestartRequestBuilder builds and executes requests for operations under \v1\inference\profiles\{profile_id}\restart
type InferenceProfilesItemRestartRequestBuilder struct {
	i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.BaseRequestBuilder
}

// InferenceProfilesItemRestartRequestBuilderPostRequestConfiguration configuration for the request such as headers, query parameters, and middleware options.
type InferenceProfilesItemRestartRequestBuilderPostRequestConfiguration struct {
	// Request headers
	Headers *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestHeaders
	// Request options
	Options []i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestOption
}

// NewInferenceProfilesItemRestartRequestBuilderInternal instantiates a new InferenceProfilesItemRestartRequestBuilder and sets the default values.
func NewInferenceProfilesItemRestartRequestBuilderInternal(pathParameters map[string]string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter) *InferenceProfilesItemRestartRequestBuilder {
	m := &InferenceProfilesItemRestartRequestBuilder{
		BaseRequestBuilder: *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewBaseRequestBuilder(requestAdapter, "{+baseurl}/v1/inference/profiles/{profile_id}/restart", pathParameters),
	}
	return m
}

// NewInferenceProfilesItemRestartRequestBuilder instantiates a new InferenceProfilesItemRestartRequestBuilder and sets the default values.
func NewInferenceProfilesItemRestartRequestBuilder(rawUrl string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter) *InferenceProfilesItemRestartRequestBuilder {
	urlParams := make(map[string]string)
	urlParams["request-raw-url"] = rawUrl
	return NewInferenceProfilesItemRestartRequestBuilderInternal(urlParams, requestAdapter)
}

// Post replace this profile's worker so it restores from its last checkpoint, coming backwith the KV cache it had in about a minute rather than eleven.
// returns a CheckpointRequestViewable when successful
func (m *InferenceProfilesItemRestartRequestBuilder) Post(ctx context.Context, requestConfiguration *InferenceProfilesItemRestartRequestBuilderPostRequestConfiguration) (i4db02de4fa95db6167263a0a43a6a58c23904074eb83cc381a94eba9021abdb2.CheckpointRequestViewable, error) {
	requestInfo, err := m.ToPostRequestInformation(ctx, requestConfiguration)
	if err != nil {
		return nil, err
	}
	res, err := m.BaseRequestBuilder.RequestAdapter.Send(ctx, requestInfo, i4db02de4fa95db6167263a0a43a6a58c23904074eb83cc381a94eba9021abdb2.CreateCheckpointRequestViewFromDiscriminatorValue, nil)
	if err != nil {
		return nil, err
	}
	if res == nil {
		return nil, nil
	}
	return res.(i4db02de4fa95db6167263a0a43a6a58c23904074eb83cc381a94eba9021abdb2.CheckpointRequestViewable), nil
}

// ToPostRequestInformation replace this profile's worker so it restores from its last checkpoint, coming backwith the KV cache it had in about a minute rather than eleven.
// returns a *RequestInformation when successful
func (m *InferenceProfilesItemRestartRequestBuilder) ToPostRequestInformation(ctx context.Context, requestConfiguration *InferenceProfilesItemRestartRequestBuilderPostRequestConfiguration) (*i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestInformation, error) {
	requestInfo := i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewRequestInformationWithMethodAndUrlTemplateAndPathParameters(i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.POST, m.BaseRequestBuilder.UrlTemplate, m.BaseRequestBuilder.PathParameters)
	if requestConfiguration != nil {
		requestInfo.Headers.AddAll(requestConfiguration.Headers)
		requestInfo.AddRequestOptions(requestConfiguration.Options)
	}
	requestInfo.Headers.TryAdd("Accept", "application/json")
	return requestInfo, nil
}

// WithUrl returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
// returns a *InferenceProfilesItemRestartRequestBuilder when successful
func (m *InferenceProfilesItemRestartRequestBuilder) WithUrl(rawUrl string) *InferenceProfilesItemRestartRequestBuilder {
	return NewInferenceProfilesItemRestartRequestBuilder(rawUrl, m.BaseRequestBuilder.RequestAdapter)
}
