// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package v1

import (
    "context"
    i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f "github.com/microsoft/kiota-abstractions-go"
)

// SlurmCheckpointPathRequestBuilder builds and executes requests for operations under \v1\slurm\checkpoint\path
type SlurmCheckpointPathRequestBuilder struct {
    i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.BaseRequestBuilder
}
// SlurmCheckpointPathRequestBuilderGetRequestConfiguration configuration for the request such as headers, query parameters, and middleware options.
type SlurmCheckpointPathRequestBuilderGetRequestConfiguration struct {
    // Request headers
    Headers *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestHeaders
    // Request options
    Options []i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestOption
}
// NewSlurmCheckpointPathRequestBuilderInternal instantiates a new SlurmCheckpointPathRequestBuilder and sets the default values.
func NewSlurmCheckpointPathRequestBuilderInternal(pathParameters map[string]string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter)(*SlurmCheckpointPathRequestBuilder) {
    m := &SlurmCheckpointPathRequestBuilder{
        BaseRequestBuilder: *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewBaseRequestBuilder(requestAdapter, "{+baseurl}/v1/slurm/checkpoint/path", pathParameters),
    }
    return m
}
// NewSlurmCheckpointPathRequestBuilder instantiates a new SlurmCheckpointPathRequestBuilder and sets the default values.
func NewSlurmCheckpointPathRequestBuilder(rawUrl string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter)(*SlurmCheckpointPathRequestBuilder) {
    urlParams := make(map[string]string)
    urlParams["request-raw-url"] = rawUrl
    return NewSlurmCheckpointPathRequestBuilderInternal(urlParams, requestAdapter)
}
// Get returns the path of the latest successful checkpoint for a given checkpoint name
// returns a *string when successful
func (m *SlurmCheckpointPathRequestBuilder) Get(ctx context.Context, requestConfiguration *SlurmCheckpointPathRequestBuilderGetRequestConfiguration)(*string, error) {
    requestInfo, err := m.ToGetRequestInformation(ctx, requestConfiguration);
    if err != nil {
        return nil, err
    }
    res, err := m.BaseRequestBuilder.RequestAdapter.SendPrimitive(ctx, requestInfo, "string", nil)
    if err != nil {
        return nil, err
    }
    if res == nil {
        return nil, nil
    }
    return res.(*string), nil
}
// ToGetRequestInformation returns the path of the latest successful checkpoint for a given checkpoint name
// returns a *RequestInformation when successful
func (m *SlurmCheckpointPathRequestBuilder) ToGetRequestInformation(ctx context.Context, requestConfiguration *SlurmCheckpointPathRequestBuilderGetRequestConfiguration)(*i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestInformation, error) {
    requestInfo := i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewRequestInformationWithMethodAndUrlTemplateAndPathParameters(i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.GET, m.BaseRequestBuilder.UrlTemplate, m.BaseRequestBuilder.PathParameters)
    if requestConfiguration != nil {
        requestInfo.Headers.AddAll(requestConfiguration.Headers)
        requestInfo.AddRequestOptions(requestConfiguration.Options)
    }
    requestInfo.Headers.TryAdd("Accept", "text/plain;q=0.9")
    return requestInfo, nil
}
// WithUrl returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
// returns a *SlurmCheckpointPathRequestBuilder when successful
func (m *SlurmCheckpointPathRequestBuilder) WithUrl(rawUrl string)(*SlurmCheckpointPathRequestBuilder) {
    return NewSlurmCheckpointPathRequestBuilder(rawUrl, m.BaseRequestBuilder.RequestAdapter);
}
