// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package v2

import (
    "context"
    i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f "github.com/microsoft/kiota-abstractions-go"
    i4db02de4fa95db6167263a0a43a6a58c23904074eb83cc381a94eba9021abdb2 "github.com/cedana/cedana-go-sdk/models"
)

// CedanaJobCheckpointsRequestBuilder builds and executes requests for operations under \v2\cedana\job\checkpoints
type CedanaJobCheckpointsRequestBuilder struct {
    i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.BaseRequestBuilder
}
// CedanaJobCheckpointsRequestBuilderGetQueryParameters supports filtering by `ids` and/or `jids` (comma-separated lists)
type CedanaJobCheckpointsRequestBuilderGetQueryParameters struct {
    // Comma-separated list of checkpoint UUIDs to filter by
    Ids *string `uriparametername:"ids"`
    // Comma-separated list of job IDs to filter by
    Jids *string `uriparametername:"jids"`
}
// CedanaJobCheckpointsRequestBuilderGetRequestConfiguration configuration for the request such as headers, query parameters, and middleware options.
type CedanaJobCheckpointsRequestBuilderGetRequestConfiguration struct {
    // Request headers
    Headers *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestHeaders
    // Request options
    Options []i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestOption
    // Request query parameters
    QueryParameters *CedanaJobCheckpointsRequestBuilderGetQueryParameters
}
// ById gets an item from the github.com/cedana/cedana-go-sdk.v2.cedana.job.checkpoints.item collection
// returns a *CedanaJobCheckpointsCheckpointsItemRequestBuilder when successful
func (m *CedanaJobCheckpointsRequestBuilder) ById(id string)(*CedanaJobCheckpointsCheckpointsItemRequestBuilder) {
    urlTplParams := make(map[string]string)
    for idx, item := range m.BaseRequestBuilder.PathParameters {
        urlTplParams[idx] = item
    }
    if id != "" {
        urlTplParams["id"] = id
    }
    return NewCedanaJobCheckpointsCheckpointsItemRequestBuilderInternal(urlTplParams, m.BaseRequestBuilder.RequestAdapter)
}
// NewCedanaJobCheckpointsRequestBuilderInternal instantiates a new CedanaJobCheckpointsRequestBuilder and sets the default values.
func NewCedanaJobCheckpointsRequestBuilderInternal(pathParameters map[string]string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter)(*CedanaJobCheckpointsRequestBuilder) {
    m := &CedanaJobCheckpointsRequestBuilder{
        BaseRequestBuilder: *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewBaseRequestBuilder(requestAdapter, "{+baseurl}/v2/cedana/job/checkpoints{?ids*,jids*}", pathParameters),
    }
    return m
}
// NewCedanaJobCheckpointsRequestBuilder instantiates a new CedanaJobCheckpointsRequestBuilder and sets the default values.
func NewCedanaJobCheckpointsRequestBuilder(rawUrl string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter)(*CedanaJobCheckpointsRequestBuilder) {
    urlParams := make(map[string]string)
    urlParams["request-raw-url"] = rawUrl
    return NewCedanaJobCheckpointsRequestBuilderInternal(urlParams, requestAdapter)
}
// Get supports filtering by `ids` and/or `jids` (comma-separated lists)
// returns a []CedanaJobCheckpointable when successful
func (m *CedanaJobCheckpointsRequestBuilder) Get(ctx context.Context, requestConfiguration *CedanaJobCheckpointsRequestBuilderGetRequestConfiguration)([]i4db02de4fa95db6167263a0a43a6a58c23904074eb83cc381a94eba9021abdb2.CedanaJobCheckpointable, error) {
    requestInfo, err := m.ToGetRequestInformation(ctx, requestConfiguration);
    if err != nil {
        return nil, err
    }
    res, err := m.BaseRequestBuilder.RequestAdapter.SendCollection(ctx, requestInfo, i4db02de4fa95db6167263a0a43a6a58c23904074eb83cc381a94eba9021abdb2.CreateCedanaJobCheckpointFromDiscriminatorValue, nil)
    if err != nil {
        return nil, err
    }
    val := make([]i4db02de4fa95db6167263a0a43a6a58c23904074eb83cc381a94eba9021abdb2.CedanaJobCheckpointable, len(res))
    for i, v := range res {
        if v != nil {
            val[i] = v.(i4db02de4fa95db6167263a0a43a6a58c23904074eb83cc381a94eba9021abdb2.CedanaJobCheckpointable)
        }
    }
    return val, nil
}
// ToGetRequestInformation supports filtering by `ids` and/or `jids` (comma-separated lists)
// returns a *RequestInformation when successful
func (m *CedanaJobCheckpointsRequestBuilder) ToGetRequestInformation(ctx context.Context, requestConfiguration *CedanaJobCheckpointsRequestBuilderGetRequestConfiguration)(*i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestInformation, error) {
    requestInfo := i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewRequestInformationWithMethodAndUrlTemplateAndPathParameters(i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.GET, m.BaseRequestBuilder.UrlTemplate, m.BaseRequestBuilder.PathParameters)
    if requestConfiguration != nil {
        if requestConfiguration.QueryParameters != nil {
            requestInfo.AddQueryParameters(*(requestConfiguration.QueryParameters))
        }
        requestInfo.Headers.AddAll(requestConfiguration.Headers)
        requestInfo.AddRequestOptions(requestConfiguration.Options)
    }
    requestInfo.Headers.TryAdd("Accept", "application/json")
    return requestInfo, nil
}
// WithUrl returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
// returns a *CedanaJobCheckpointsRequestBuilder when successful
func (m *CedanaJobCheckpointsRequestBuilder) WithUrl(rawUrl string)(*CedanaJobCheckpointsRequestBuilder) {
    return NewCedanaJobCheckpointsRequestBuilder(rawUrl, m.BaseRequestBuilder.RequestAdapter);
}
