// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package v2

import (
    "context"
    i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f "github.com/microsoft/kiota-abstractions-go"
    i4db02de4fa95db6167263a0a43a6a58c23904074eb83cc381a94eba9021abdb2 "github.com/cedana/cedana-go-sdk/models"
)

// DynamoDeploymentsItemMetricsRequestBuilder builds and executes requests for operations under \v2\dynamo\deployments\{name}\metrics
type DynamoDeploymentsItemMetricsRequestBuilder struct {
    i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.BaseRequestBuilder
}
// DynamoDeploymentsItemMetricsRequestBuilderGetQueryParameters query Dynamo inference metrics for a deployment.
type DynamoDeploymentsItemMetricsRequestBuilderGetQueryParameters struct {
    Cluster_id *string `uriparametername:"cluster_id"`
    // Optional absolute range start (Unix ms). If set with `to_ms`, overrides `hours`.
    From_ms *int64 `uriparametername:"from_ms"`
    // Relative time window in hours. Default 1, max 720 (30 days, matching themetrics TTL). When `from_ms`/`to_ms` are given they take precedence andthis is ignored. For a deleted deployment the relative window is anchoredto the deployment's LATEST datapoint (not `now()`), so historical data isstill returned instead of an empty window that has scrolled past it.
    Hours *int32 `uriparametername:"hours"`
    Namespace *string `uriparametername:"namespace"`
    // Optional absolute range end (Unix ms). If set with `from_ms`, overrides `hours`.
    To_ms *int64 `uriparametername:"to_ms"`
}
// DynamoDeploymentsItemMetricsRequestBuilderGetRequestConfiguration configuration for the request such as headers, query parameters, and middleware options.
type DynamoDeploymentsItemMetricsRequestBuilderGetRequestConfiguration struct {
    // Request headers
    Headers *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestHeaders
    // Request options
    Options []i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestOption
    // Request query parameters
    QueryParameters *DynamoDeploymentsItemMetricsRequestBuilderGetQueryParameters
}
// DynamoDeploymentsItemMetricsRequestBuilderPostRequestConfiguration configuration for the request such as headers, query parameters, and middleware options.
type DynamoDeploymentsItemMetricsRequestBuilderPostRequestConfiguration struct {
    // Request headers
    Headers *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestHeaders
    // Request options
    Options []i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestOption
}
// NewDynamoDeploymentsItemMetricsRequestBuilderInternal instantiates a new DynamoDeploymentsItemMetricsRequestBuilder and sets the default values.
func NewDynamoDeploymentsItemMetricsRequestBuilderInternal(pathParameters map[string]string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter)(*DynamoDeploymentsItemMetricsRequestBuilder) {
    m := &DynamoDeploymentsItemMetricsRequestBuilder{
        BaseRequestBuilder: *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewBaseRequestBuilder(requestAdapter, "{+baseurl}/v2/dynamo/deployments/{name}/metrics{?cluster_id*,from_ms*,hours*,namespace*,to_ms*}", pathParameters),
    }
    return m
}
// NewDynamoDeploymentsItemMetricsRequestBuilder instantiates a new DynamoDeploymentsItemMetricsRequestBuilder and sets the default values.
func NewDynamoDeploymentsItemMetricsRequestBuilder(rawUrl string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter)(*DynamoDeploymentsItemMetricsRequestBuilder) {
    urlParams := make(map[string]string)
    urlParams["request-raw-url"] = rawUrl
    return NewDynamoDeploymentsItemMetricsRequestBuilderInternal(urlParams, requestAdapter)
}
// Get query Dynamo inference metrics for a deployment.
// returns a []DynamoMetricPointable when successful
func (m *DynamoDeploymentsItemMetricsRequestBuilder) Get(ctx context.Context, requestConfiguration *DynamoDeploymentsItemMetricsRequestBuilderGetRequestConfiguration)([]i4db02de4fa95db6167263a0a43a6a58c23904074eb83cc381a94eba9021abdb2.DynamoMetricPointable, error) {
    requestInfo, err := m.ToGetRequestInformation(ctx, requestConfiguration);
    if err != nil {
        return nil, err
    }
    res, err := m.BaseRequestBuilder.RequestAdapter.SendCollection(ctx, requestInfo, i4db02de4fa95db6167263a0a43a6a58c23904074eb83cc381a94eba9021abdb2.CreateDynamoMetricPointFromDiscriminatorValue, nil)
    if err != nil {
        return nil, err
    }
    val := make([]i4db02de4fa95db6167263a0a43a6a58c23904074eb83cc381a94eba9021abdb2.DynamoMetricPointable, len(res))
    for i, v := range res {
        if v != nil {
            val[i] = v.(i4db02de4fa95db6167263a0a43a6a58c23904074eb83cc381a94eba9021abdb2.DynamoMetricPointable)
        }
    }
    return val, nil
}
// Post ingest a batch of Dynamo inference metrics from the watcher.
// returns a *string when successful
func (m *DynamoDeploymentsItemMetricsRequestBuilder) Post(ctx context.Context, body i4db02de4fa95db6167263a0a43a6a58c23904074eb83cc381a94eba9021abdb2.DynamoMetricsIngestRequestable, requestConfiguration *DynamoDeploymentsItemMetricsRequestBuilderPostRequestConfiguration)(*string, error) {
    requestInfo, err := m.ToPostRequestInformation(ctx, body, requestConfiguration);
    if err != nil {
        return nil, err
    }
    res, err := m.BaseRequestBuilder.RequestAdapter.SendPrimitive(ctx, requestInfo, "string", nil)
    if err != nil {
        return nil, err
    }
    if res == nil {
        return nil, nil
    }
    return res.(*string), nil
}
// ToGetRequestInformation query Dynamo inference metrics for a deployment.
// returns a *RequestInformation when successful
func (m *DynamoDeploymentsItemMetricsRequestBuilder) ToGetRequestInformation(ctx context.Context, requestConfiguration *DynamoDeploymentsItemMetricsRequestBuilderGetRequestConfiguration)(*i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestInformation, error) {
    requestInfo := i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewRequestInformationWithMethodAndUrlTemplateAndPathParameters(i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.GET, m.BaseRequestBuilder.UrlTemplate, m.BaseRequestBuilder.PathParameters)
    if requestConfiguration != nil {
        if requestConfiguration.QueryParameters != nil {
            requestInfo.AddQueryParameters(*(requestConfiguration.QueryParameters))
        }
        requestInfo.Headers.AddAll(requestConfiguration.Headers)
        requestInfo.AddRequestOptions(requestConfiguration.Options)
    }
    requestInfo.Headers.TryAdd("Accept", "application/json")
    return requestInfo, nil
}
// ToPostRequestInformation ingest a batch of Dynamo inference metrics from the watcher.
// returns a *RequestInformation when successful
func (m *DynamoDeploymentsItemMetricsRequestBuilder) ToPostRequestInformation(ctx context.Context, body i4db02de4fa95db6167263a0a43a6a58c23904074eb83cc381a94eba9021abdb2.DynamoMetricsIngestRequestable, requestConfiguration *DynamoDeploymentsItemMetricsRequestBuilderPostRequestConfiguration)(*i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestInformation, error) {
    requestInfo := i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewRequestInformationWithMethodAndUrlTemplateAndPathParameters(i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.POST, m.BaseRequestBuilder.UrlTemplate, m.BaseRequestBuilder.PathParameters)
    if requestConfiguration != nil {
        requestInfo.Headers.AddAll(requestConfiguration.Headers)
        requestInfo.AddRequestOptions(requestConfiguration.Options)
    }
    requestInfo.Headers.TryAdd("Accept", "text/plain;q=0.9")
    err := requestInfo.SetContentFromParsable(ctx, m.BaseRequestBuilder.RequestAdapter, "application/json", body)
    if err != nil {
        return nil, err
    }
    return requestInfo, nil
}
// WithUrl returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
// returns a *DynamoDeploymentsItemMetricsRequestBuilder when successful
func (m *DynamoDeploymentsItemMetricsRequestBuilder) WithUrl(rawUrl string)(*DynamoDeploymentsItemMetricsRequestBuilder) {
    return NewDynamoDeploymentsItemMetricsRequestBuilder(rawUrl, m.BaseRequestBuilder.RequestAdapter);
}
