// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package v2

import (
    i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f "github.com/microsoft/kiota-abstractions-go"
)

// JobRequestBuilder builds and executes requests for operations under \v2\job
type JobRequestBuilder struct {
    i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.BaseRequestBuilder
}
// NewJobRequestBuilderInternal instantiates a new JobRequestBuilder and sets the default values.
func NewJobRequestBuilderInternal(pathParameters map[string]string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter)(*JobRequestBuilder) {
    m := &JobRequestBuilder{
        BaseRequestBuilder: *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewBaseRequestBuilder(requestAdapter, "{+baseurl}/v2/job", pathParameters),
    }
    return m
}
// NewJobRequestBuilder instantiates a new JobRequestBuilder and sets the default values.
func NewJobRequestBuilder(rawUrl string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter)(*JobRequestBuilder) {
    urlParams := make(map[string]string)
    urlParams["request-raw-url"] = rawUrl
    return NewJobRequestBuilderInternal(urlParams, requestAdapter)
}
// DeletePath the deletePath property
// returns a *JobDeleteRequestBuilder when successful
func (m *JobRequestBuilder) DeletePath()(*JobDeleteRequestBuilder) {
    return NewJobDeleteRequestBuilderInternal(m.BaseRequestBuilder.PathParameters, m.BaseRequestBuilder.RequestAdapter)
}
// Upload the upload property
// returns a *JobUploadRequestBuilder when successful
func (m *JobRequestBuilder) Upload()(*JobUploadRequestBuilder) {
    return NewJobUploadRequestBuilderInternal(m.BaseRequestBuilder.PathParameters, m.BaseRequestBuilder.RequestAdapter)
}
