// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package v2

import (
    "context"
    i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f "github.com/microsoft/kiota-abstractions-go"
    i4db02de4fa95db6167263a0a43a6a58c23904074eb83cc381a94eba9021abdb2 "github.com/cedana/cedana-go-sdk/models"
)

// JobsPaginatedRequestBuilder builds and executes requests for operations under \v2\jobs\paginated
type JobsPaginatedRequestBuilder struct {
    i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.BaseRequestBuilder
}
// JobsPaginatedRequestBuilderGetQueryParameters list jobs (paginated)
type JobsPaginatedRequestBuilderGetQueryParameters struct {
    Ascending *bool `uriparametername:"ascending"`
    // job name to query against (uses postgres ILIKE pattern search)
    Job_name *string `uriparametername:"job_name"`
    Limit *int64 `uriparametername:"limit"`
    Namespace *string `uriparametername:"namespace"`
    Offset *int64 `uriparametername:"offset"`
    Sort *string `uriparametername:"sort"`
    Status *string `uriparametername:"status"`
}
// JobsPaginatedRequestBuilderGetRequestConfiguration configuration for the request such as headers, query parameters, and middleware options.
type JobsPaginatedRequestBuilderGetRequestConfiguration struct {
    // Request headers
    Headers *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestHeaders
    // Request options
    Options []i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestOption
    // Request query parameters
    QueryParameters *JobsPaginatedRequestBuilderGetQueryParameters
}
// NewJobsPaginatedRequestBuilderInternal instantiates a new JobsPaginatedRequestBuilder and sets the default values.
func NewJobsPaginatedRequestBuilderInternal(pathParameters map[string]string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter)(*JobsPaginatedRequestBuilder) {
    m := &JobsPaginatedRequestBuilder{
        BaseRequestBuilder: *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewBaseRequestBuilder(requestAdapter, "{+baseurl}/v2/jobs/paginated{?ascending*,job_name*,limit*,namespace*,offset*,sort*,status*}", pathParameters),
    }
    return m
}
// NewJobsPaginatedRequestBuilder instantiates a new JobsPaginatedRequestBuilder and sets the default values.
func NewJobsPaginatedRequestBuilder(rawUrl string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter)(*JobsPaginatedRequestBuilder) {
    urlParams := make(map[string]string)
    urlParams["request-raw-url"] = rawUrl
    return NewJobsPaginatedRequestBuilderInternal(urlParams, requestAdapter)
}
// Get list jobs (paginated)
// returns a PaginatedJobResponseable when successful
// returns a ApiError error when the service returns a 500 status code
func (m *JobsPaginatedRequestBuilder) Get(ctx context.Context, requestConfiguration *JobsPaginatedRequestBuilderGetRequestConfiguration)(i4db02de4fa95db6167263a0a43a6a58c23904074eb83cc381a94eba9021abdb2.PaginatedJobResponseable, error) {
    requestInfo, err := m.ToGetRequestInformation(ctx, requestConfiguration);
    if err != nil {
        return nil, err
    }
    errorMapping := i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.ErrorMappings {
        "500": i4db02de4fa95db6167263a0a43a6a58c23904074eb83cc381a94eba9021abdb2.CreateApiErrorFromDiscriminatorValue,
    }
    res, err := m.BaseRequestBuilder.RequestAdapter.Send(ctx, requestInfo, i4db02de4fa95db6167263a0a43a6a58c23904074eb83cc381a94eba9021abdb2.CreatePaginatedJobResponseFromDiscriminatorValue, errorMapping)
    if err != nil {
        return nil, err
    }
    if res == nil {
        return nil, nil
    }
    return res.(i4db02de4fa95db6167263a0a43a6a58c23904074eb83cc381a94eba9021abdb2.PaginatedJobResponseable), nil
}
// ToGetRequestInformation list jobs (paginated)
// returns a *RequestInformation when successful
func (m *JobsPaginatedRequestBuilder) ToGetRequestInformation(ctx context.Context, requestConfiguration *JobsPaginatedRequestBuilderGetRequestConfiguration)(*i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestInformation, error) {
    requestInfo := i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewRequestInformationWithMethodAndUrlTemplateAndPathParameters(i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.GET, m.BaseRequestBuilder.UrlTemplate, m.BaseRequestBuilder.PathParameters)
    if requestConfiguration != nil {
        if requestConfiguration.QueryParameters != nil {
            requestInfo.AddQueryParameters(*(requestConfiguration.QueryParameters))
        }
        requestInfo.Headers.AddAll(requestConfiguration.Headers)
        requestInfo.AddRequestOptions(requestConfiguration.Options)
    }
    requestInfo.Headers.TryAdd("Accept", "application/json")
    return requestInfo, nil
}
// WithUrl returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
// returns a *JobsPaginatedRequestBuilder when successful
func (m *JobsPaginatedRequestBuilder) WithUrl(rawUrl string)(*JobsPaginatedRequestBuilder) {
    return NewJobsPaginatedRequestBuilder(rawUrl, m.BaseRequestBuilder.RequestAdapter);
}
