// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package v2

import (
    "context"
    i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f "github.com/microsoft/kiota-abstractions-go"
    i4db02de4fa95db6167263a0a43a6a58c23904074eb83cc381a94eba9021abdb2 "github.com/cedana/cedana-go-sdk/models"
)

// JobsPrioritiesRequestBuilder builds and executes requests for operations under \v2\jobs\priorities
type JobsPrioritiesRequestBuilder struct {
    i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.BaseRequestBuilder
}
// JobsPrioritiesRequestBuilderGetRequestConfiguration configuration for the request such as headers, query parameters, and middleware options.
type JobsPrioritiesRequestBuilderGetRequestConfiguration struct {
    // Request headers
    Headers *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestHeaders
    // Request options
    Options []i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestOption
}
// NewJobsPrioritiesRequestBuilderInternal instantiates a new JobsPrioritiesRequestBuilder and sets the default values.
func NewJobsPrioritiesRequestBuilderInternal(pathParameters map[string]string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter)(*JobsPrioritiesRequestBuilder) {
    m := &JobsPrioritiesRequestBuilder{
        BaseRequestBuilder: *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewBaseRequestBuilder(requestAdapter, "{+baseurl}/v2/jobs/priorities", pathParameters),
    }
    return m
}
// NewJobsPrioritiesRequestBuilder instantiates a new JobsPrioritiesRequestBuilder and sets the default values.
func NewJobsPrioritiesRequestBuilder(rawUrl string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter)(*JobsPrioritiesRequestBuilder) {
    urlParams := make(map[string]string)
    urlParams["request-raw-url"] = rawUrl
    return NewJobsPrioritiesRequestBuilderInternal(urlParams, requestAdapter)
}
// Get get available job priorities with counts
// returns a JobPrioritiesResponseable when successful
func (m *JobsPrioritiesRequestBuilder) Get(ctx context.Context, requestConfiguration *JobsPrioritiesRequestBuilderGetRequestConfiguration)(i4db02de4fa95db6167263a0a43a6a58c23904074eb83cc381a94eba9021abdb2.JobPrioritiesResponseable, error) {
    requestInfo, err := m.ToGetRequestInformation(ctx, requestConfiguration);
    if err != nil {
        return nil, err
    }
    res, err := m.BaseRequestBuilder.RequestAdapter.Send(ctx, requestInfo, i4db02de4fa95db6167263a0a43a6a58c23904074eb83cc381a94eba9021abdb2.CreateJobPrioritiesResponseFromDiscriminatorValue, nil)
    if err != nil {
        return nil, err
    }
    if res == nil {
        return nil, nil
    }
    return res.(i4db02de4fa95db6167263a0a43a6a58c23904074eb83cc381a94eba9021abdb2.JobPrioritiesResponseable), nil
}
// ToGetRequestInformation get available job priorities with counts
// returns a *RequestInformation when successful
func (m *JobsPrioritiesRequestBuilder) ToGetRequestInformation(ctx context.Context, requestConfiguration *JobsPrioritiesRequestBuilderGetRequestConfiguration)(*i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestInformation, error) {
    requestInfo := i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewRequestInformationWithMethodAndUrlTemplateAndPathParameters(i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.GET, m.BaseRequestBuilder.UrlTemplate, m.BaseRequestBuilder.PathParameters)
    if requestConfiguration != nil {
        requestInfo.Headers.AddAll(requestConfiguration.Headers)
        requestInfo.AddRequestOptions(requestConfiguration.Options)
    }
    requestInfo.Headers.TryAdd("Accept", "application/json")
    return requestInfo, nil
}
// WithUrl returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
// returns a *JobsPrioritiesRequestBuilder when successful
func (m *JobsPrioritiesRequestBuilder) WithUrl(rawUrl string)(*JobsPrioritiesRequestBuilder) {
    return NewJobsPrioritiesRequestBuilder(rawUrl, m.BaseRequestBuilder.RequestAdapter);
}
