// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package v2

import (
    i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f "github.com/microsoft/kiota-abstractions-go"
)

// K8sRequestBuilder builds and executes requests for operations under \v2\k8s
type K8sRequestBuilder struct {
    i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.BaseRequestBuilder
}
// NewK8sRequestBuilderInternal instantiates a new K8sRequestBuilder and sets the default values.
func NewK8sRequestBuilderInternal(pathParameters map[string]string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter)(*K8sRequestBuilder) {
    m := &K8sRequestBuilder{
        BaseRequestBuilder: *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewBaseRequestBuilder(requestAdapter, "{+baseurl}/v2/k8s", pathParameters),
    }
    return m
}
// NewK8sRequestBuilder instantiates a new K8sRequestBuilder and sets the default values.
func NewK8sRequestBuilder(rawUrl string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter)(*K8sRequestBuilder) {
    urlParams := make(map[string]string)
    urlParams["request-raw-url"] = rawUrl
    return NewK8sRequestBuilderInternal(urlParams, requestAdapter)
}
// Sync the sync property
// returns a *K8sSyncRequestBuilder when successful
func (m *K8sRequestBuilder) Sync()(*K8sSyncRequestBuilder) {
    return NewK8sSyncRequestBuilderInternal(m.BaseRequestBuilder.PathParameters, m.BaseRequestBuilder.RequestAdapter)
}
