// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package v2

import (
    "context"
    i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f "github.com/microsoft/kiota-abstractions-go"
    i4db02de4fa95db6167263a0a43a6a58c23904074eb83cc381a94eba9021abdb2 "github.com/cedana/cedana-go-sdk/models"
)

// SlurmJobs_paginatedRequestBuilder builds and executes requests for operations under \v2\slurm\jobs_paginated
type SlurmJobs_paginatedRequestBuilder struct {
    i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.BaseRequestBuilder
}
// SlurmJobs_paginatedRequestBuilderGetQueryParameters use query params to filter jobs
type SlurmJobs_paginatedRequestBuilderGetQueryParameters struct {
    // Maximum number of records to return (default: 50, max: 100)
    Limit *int32 `uriparametername:"limit"`
    // Number of records to skip (default: 0)
    Offset *int32 `uriparametername:"offset"`
}
// SlurmJobs_paginatedRequestBuilderGetRequestConfiguration configuration for the request such as headers, query parameters, and middleware options.
type SlurmJobs_paginatedRequestBuilderGetRequestConfiguration struct {
    // Request headers
    Headers *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestHeaders
    // Request options
    Options []i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestOption
    // Request query parameters
    QueryParameters *SlurmJobs_paginatedRequestBuilderGetQueryParameters
}
// NewSlurmJobs_paginatedRequestBuilderInternal instantiates a new SlurmJobs_paginatedRequestBuilder and sets the default values.
func NewSlurmJobs_paginatedRequestBuilderInternal(pathParameters map[string]string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter)(*SlurmJobs_paginatedRequestBuilder) {
    m := &SlurmJobs_paginatedRequestBuilder{
        BaseRequestBuilder: *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewBaseRequestBuilder(requestAdapter, "{+baseurl}/v2/slurm/jobs_paginated{?limit*,offset*}", pathParameters),
    }
    return m
}
// NewSlurmJobs_paginatedRequestBuilder instantiates a new SlurmJobs_paginatedRequestBuilder and sets the default values.
func NewSlurmJobs_paginatedRequestBuilder(rawUrl string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter)(*SlurmJobs_paginatedRequestBuilder) {
    urlParams := make(map[string]string)
    urlParams["request-raw-url"] = rawUrl
    return NewSlurmJobs_paginatedRequestBuilderInternal(urlParams, requestAdapter)
}
// Get use query params to filter jobs
// returns a []SlurmJobable when successful
func (m *SlurmJobs_paginatedRequestBuilder) Get(ctx context.Context, requestConfiguration *SlurmJobs_paginatedRequestBuilderGetRequestConfiguration)([]i4db02de4fa95db6167263a0a43a6a58c23904074eb83cc381a94eba9021abdb2.SlurmJobable, error) {
    requestInfo, err := m.ToGetRequestInformation(ctx, requestConfiguration);
    if err != nil {
        return nil, err
    }
    res, err := m.BaseRequestBuilder.RequestAdapter.SendCollection(ctx, requestInfo, i4db02de4fa95db6167263a0a43a6a58c23904074eb83cc381a94eba9021abdb2.CreateSlurmJobFromDiscriminatorValue, nil)
    if err != nil {
        return nil, err
    }
    val := make([]i4db02de4fa95db6167263a0a43a6a58c23904074eb83cc381a94eba9021abdb2.SlurmJobable, len(res))
    for i, v := range res {
        if v != nil {
            val[i] = v.(i4db02de4fa95db6167263a0a43a6a58c23904074eb83cc381a94eba9021abdb2.SlurmJobable)
        }
    }
    return val, nil
}
// ToGetRequestInformation use query params to filter jobs
// returns a *RequestInformation when successful
func (m *SlurmJobs_paginatedRequestBuilder) ToGetRequestInformation(ctx context.Context, requestConfiguration *SlurmJobs_paginatedRequestBuilderGetRequestConfiguration)(*i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestInformation, error) {
    requestInfo := i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewRequestInformationWithMethodAndUrlTemplateAndPathParameters(i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.GET, m.BaseRequestBuilder.UrlTemplate, m.BaseRequestBuilder.PathParameters)
    if requestConfiguration != nil {
        if requestConfiguration.QueryParameters != nil {
            requestInfo.AddQueryParameters(*(requestConfiguration.QueryParameters))
        }
        requestInfo.Headers.AddAll(requestConfiguration.Headers)
        requestInfo.AddRequestOptions(requestConfiguration.Options)
    }
    requestInfo.Headers.TryAdd("Accept", "application/json")
    return requestInfo, nil
}
// WithUrl returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
// returns a *SlurmJobs_paginatedRequestBuilder when successful
func (m *SlurmJobs_paginatedRequestBuilder) WithUrl(rawUrl string)(*SlurmJobs_paginatedRequestBuilder) {
    return NewSlurmJobs_paginatedRequestBuilder(rawUrl, m.BaseRequestBuilder.RequestAdapter);
}
