// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package models

import (
	i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

type ActivationReport struct {
	// Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
	additionalData map[string]any
	// The desired_state property
	desired_state *string
	// The endpoint property
	endpoint *string
	// The observed_generation property
	observed_generation *int64
	// The phase property
	phase *string
	// The profile_id property
	profile_id *string
	// The ready property
	ready *bool
}

// NewActivationReport instantiates a new ActivationReport and sets the default values.
func NewActivationReport() *ActivationReport {
	m := &ActivationReport{}
	m.SetAdditionalData(make(map[string]any))
	return m
}

// CreateActivationReportFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateActivationReportFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) (i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
	return NewActivationReport(), nil
}

// GetAdditionalData gets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
// returns a map[string]any when successful
func (m *ActivationReport) GetAdditionalData() map[string]any {
	return m.additionalData
}

// GetDesiredState gets the desired_state property value. The desired_state property
// returns a *string when successful
func (m *ActivationReport) GetDesiredState() *string {
	return m.desired_state
}

// GetEndpoint gets the endpoint property value. The endpoint property
// returns a *string when successful
func (m *ActivationReport) GetEndpoint() *string {
	return m.endpoint
}

// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error when successful
func (m *ActivationReport) GetFieldDeserializers() map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
	res := make(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error)
	res["desired_state"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetStringValue()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetDesiredState(val)
		}
		return nil
	}
	res["endpoint"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetStringValue()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetEndpoint(val)
		}
		return nil
	}
	res["observed_generation"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetInt64Value()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetObservedGeneration(val)
		}
		return nil
	}
	res["phase"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetStringValue()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetPhase(val)
		}
		return nil
	}
	res["profile_id"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetStringValue()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetProfileId(val)
		}
		return nil
	}
	res["ready"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetBoolValue()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetReady(val)
		}
		return nil
	}
	return res
}

// GetObservedGeneration gets the observed_generation property value. The observed_generation property
// returns a *int64 when successful
func (m *ActivationReport) GetObservedGeneration() *int64 {
	return m.observed_generation
}

// GetPhase gets the phase property value. The phase property
// returns a *string when successful
func (m *ActivationReport) GetPhase() *string {
	return m.phase
}

// GetProfileId gets the profile_id property value. The profile_id property
// returns a *string when successful
func (m *ActivationReport) GetProfileId() *string {
	return m.profile_id
}

// GetReady gets the ready property value. The ready property
// returns a *bool when successful
func (m *ActivationReport) GetReady() *bool {
	return m.ready
}

// Serialize serializes information the current object
func (m *ActivationReport) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter) error {
	{
		err := writer.WriteStringValue("desired_state", m.GetDesiredState())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteStringValue("endpoint", m.GetEndpoint())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteInt64Value("observed_generation", m.GetObservedGeneration())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteStringValue("phase", m.GetPhase())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteStringValue("profile_id", m.GetProfileId())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteBoolValue("ready", m.GetReady())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteAdditionalData(m.GetAdditionalData())
		if err != nil {
			return err
		}
	}
	return nil
}

// SetAdditionalData sets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
func (m *ActivationReport) SetAdditionalData(value map[string]any) {
	m.additionalData = value
}

// SetDesiredState sets the desired_state property value. The desired_state property
func (m *ActivationReport) SetDesiredState(value *string) {
	m.desired_state = value
}

// SetEndpoint sets the endpoint property value. The endpoint property
func (m *ActivationReport) SetEndpoint(value *string) {
	m.endpoint = value
}

// SetObservedGeneration sets the observed_generation property value. The observed_generation property
func (m *ActivationReport) SetObservedGeneration(value *int64) {
	m.observed_generation = value
}

// SetPhase sets the phase property value. The phase property
func (m *ActivationReport) SetPhase(value *string) {
	m.phase = value
}

// SetProfileId sets the profile_id property value. The profile_id property
func (m *ActivationReport) SetProfileId(value *string) {
	m.profile_id = value
}

// SetReady sets the ready property value. The ready property
func (m *ActivationReport) SetReady(value *bool) {
	m.ready = value
}

type ActivationReportable interface {
	i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.AdditionalDataHolder
	i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
	GetDesiredState() *string
	GetEndpoint() *string
	GetObservedGeneration() *int64
	GetPhase() *string
	GetProfileId() *string
	GetReady() *bool
	SetDesiredState(value *string)
	SetEndpoint(value *string)
	SetObservedGeneration(value *int64)
	SetPhase(value *string)
	SetProfileId(value *string)
	SetReady(value *bool)
}
