// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package models

import (
	i561e97a8befe7661a44c8f54600992b4207a3a0cf6770e5559949bc276de2e22 "github.com/google/uuid"
	i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
	i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e "time"
)

type CapacityIntent struct {
	// Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
	additionalData map[string]any
	// When this intent row was first created. Not when the request it currentlydescribes was made: the row is reused for a repeated ask. Use requested_at for that.
	created_at *i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time
	// The deadline property
	deadline *i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time
	// The desired_replicas property
	desired_replicas *int32
	// The desired_state property
	desired_state *string
	// The generation property
	generation *int64
	// The id property
	id *i561e97a8befe7661a44c8f54600992b4207a3a0cf6770e5559949bc276de2e22.UUID
	// The profile_id property
	profile_id *string
	// When a caller last asked for this exact state and replica count, so it ordersrequests as they were made rather than as the row happened to change.
	requested_at *i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time
	// The status property
	status *string
	// When this row last changed for any reason, including the expiry sweep. Not anordering key for what a caller asked for.
	updated_at *i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time
}

// NewCapacityIntent instantiates a new CapacityIntent and sets the default values.
func NewCapacityIntent() *CapacityIntent {
	m := &CapacityIntent{}
	m.SetAdditionalData(make(map[string]any))
	return m
}

// CreateCapacityIntentFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateCapacityIntentFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) (i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
	return NewCapacityIntent(), nil
}

// GetAdditionalData gets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
// returns a map[string]any when successful
func (m *CapacityIntent) GetAdditionalData() map[string]any {
	return m.additionalData
}

// GetCreatedAt gets the created_at property value. When this intent row was first created. Not when the request it currentlydescribes was made: the row is reused for a repeated ask. Use requested_at for that.
// returns a *Time when successful
func (m *CapacityIntent) GetCreatedAt() *i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time {
	return m.created_at
}

// GetDeadline gets the deadline property value. The deadline property
// returns a *Time when successful
func (m *CapacityIntent) GetDeadline() *i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time {
	return m.deadline
}

// GetDesiredReplicas gets the desired_replicas property value. The desired_replicas property
// returns a *int32 when successful
func (m *CapacityIntent) GetDesiredReplicas() *int32 {
	return m.desired_replicas
}

// GetDesiredState gets the desired_state property value. The desired_state property
// returns a *string when successful
func (m *CapacityIntent) GetDesiredState() *string {
	return m.desired_state
}

// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error when successful
func (m *CapacityIntent) GetFieldDeserializers() map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
	res := make(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error)
	res["created_at"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetTimeValue()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetCreatedAt(val)
		}
		return nil
	}
	res["deadline"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetTimeValue()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetDeadline(val)
		}
		return nil
	}
	res["desired_replicas"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetInt32Value()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetDesiredReplicas(val)
		}
		return nil
	}
	res["desired_state"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetStringValue()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetDesiredState(val)
		}
		return nil
	}
	res["generation"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetInt64Value()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetGeneration(val)
		}
		return nil
	}
	res["id"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetUUIDValue()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetId(val)
		}
		return nil
	}
	res["profile_id"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetStringValue()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetProfileId(val)
		}
		return nil
	}
	res["requested_at"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetTimeValue()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetRequestedAt(val)
		}
		return nil
	}
	res["status"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetStringValue()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetStatus(val)
		}
		return nil
	}
	res["updated_at"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetTimeValue()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetUpdatedAt(val)
		}
		return nil
	}
	return res
}

// GetGeneration gets the generation property value. The generation property
// returns a *int64 when successful
func (m *CapacityIntent) GetGeneration() *int64 {
	return m.generation
}

// GetId gets the id property value. The id property
// returns a *UUID when successful
func (m *CapacityIntent) GetId() *i561e97a8befe7661a44c8f54600992b4207a3a0cf6770e5559949bc276de2e22.UUID {
	return m.id
}

// GetProfileId gets the profile_id property value. The profile_id property
// returns a *string when successful
func (m *CapacityIntent) GetProfileId() *string {
	return m.profile_id
}

// GetRequestedAt gets the requested_at property value. When a caller last asked for this exact state and replica count, so it ordersrequests as they were made rather than as the row happened to change.
// returns a *Time when successful
func (m *CapacityIntent) GetRequestedAt() *i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time {
	return m.requested_at
}

// GetStatus gets the status property value. The status property
// returns a *string when successful
func (m *CapacityIntent) GetStatus() *string {
	return m.status
}

// GetUpdatedAt gets the updated_at property value. When this row last changed for any reason, including the expiry sweep. Not anordering key for what a caller asked for.
// returns a *Time when successful
func (m *CapacityIntent) GetUpdatedAt() *i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time {
	return m.updated_at
}

// Serialize serializes information the current object
func (m *CapacityIntent) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter) error {
	{
		err := writer.WriteTimeValue("created_at", m.GetCreatedAt())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteTimeValue("deadline", m.GetDeadline())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteInt32Value("desired_replicas", m.GetDesiredReplicas())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteStringValue("desired_state", m.GetDesiredState())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteInt64Value("generation", m.GetGeneration())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteUUIDValue("id", m.GetId())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteStringValue("profile_id", m.GetProfileId())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteTimeValue("requested_at", m.GetRequestedAt())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteStringValue("status", m.GetStatus())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteTimeValue("updated_at", m.GetUpdatedAt())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteAdditionalData(m.GetAdditionalData())
		if err != nil {
			return err
		}
	}
	return nil
}

// SetAdditionalData sets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
func (m *CapacityIntent) SetAdditionalData(value map[string]any) {
	m.additionalData = value
}

// SetCreatedAt sets the created_at property value. When this intent row was first created. Not when the request it currentlydescribes was made: the row is reused for a repeated ask. Use requested_at for that.
func (m *CapacityIntent) SetCreatedAt(value *i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time) {
	m.created_at = value
}

// SetDeadline sets the deadline property value. The deadline property
func (m *CapacityIntent) SetDeadline(value *i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time) {
	m.deadline = value
}

// SetDesiredReplicas sets the desired_replicas property value. The desired_replicas property
func (m *CapacityIntent) SetDesiredReplicas(value *int32) {
	m.desired_replicas = value
}

// SetDesiredState sets the desired_state property value. The desired_state property
func (m *CapacityIntent) SetDesiredState(value *string) {
	m.desired_state = value
}

// SetGeneration sets the generation property value. The generation property
func (m *CapacityIntent) SetGeneration(value *int64) {
	m.generation = value
}

// SetId sets the id property value. The id property
func (m *CapacityIntent) SetId(value *i561e97a8befe7661a44c8f54600992b4207a3a0cf6770e5559949bc276de2e22.UUID) {
	m.id = value
}

// SetProfileId sets the profile_id property value. The profile_id property
func (m *CapacityIntent) SetProfileId(value *string) {
	m.profile_id = value
}

// SetRequestedAt sets the requested_at property value. When a caller last asked for this exact state and replica count, so it ordersrequests as they were made rather than as the row happened to change.
func (m *CapacityIntent) SetRequestedAt(value *i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time) {
	m.requested_at = value
}

// SetStatus sets the status property value. The status property
func (m *CapacityIntent) SetStatus(value *string) {
	m.status = value
}

// SetUpdatedAt sets the updated_at property value. When this row last changed for any reason, including the expiry sweep. Not anordering key for what a caller asked for.
func (m *CapacityIntent) SetUpdatedAt(value *i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time) {
	m.updated_at = value
}

type CapacityIntentable interface {
	i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.AdditionalDataHolder
	i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
	GetCreatedAt() *i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time
	GetDeadline() *i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time
	GetDesiredReplicas() *int32
	GetDesiredState() *string
	GetGeneration() *int64
	GetId() *i561e97a8befe7661a44c8f54600992b4207a3a0cf6770e5559949bc276de2e22.UUID
	GetProfileId() *string
	GetRequestedAt() *i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time
	GetStatus() *string
	GetUpdatedAt() *i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time
	SetCreatedAt(value *i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time)
	SetDeadline(value *i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time)
	SetDesiredReplicas(value *int32)
	SetDesiredState(value *string)
	SetGeneration(value *int64)
	SetId(value *i561e97a8befe7661a44c8f54600992b4207a3a0cf6770e5559949bc276de2e22.UUID)
	SetProfileId(value *string)
	SetRequestedAt(value *i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time)
	SetStatus(value *string)
	SetUpdatedAt(value *i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time)
}
