// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package models

import (
	i561e97a8befe7661a44c8f54600992b4207a3a0cf6770e5559949bc276de2e22 "github.com/google/uuid"
	i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

type CorrelationView struct {
	// The activations property
	activations []NameCountable
	// Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
	additionalData map[string]any
	// The artifacts property
	artifacts []ArtifactRefable
	// The experiment_id property
	experiment_id *i561e97a8befe7661a44c8f54600992b4207a3a0cf6770e5559949bc276de2e22.UUID
	// The intents property
	intents []NameCountable
	// The name property
	name *string
	// The observations property
	observations []NameCountable
	// The policy_decisions property
	policy_decisions []NameCountable
	// The scenario property
	scenario *string
	// The status property
	status *string
	// The usage property
	usage CorrelationUsageable
}

// NewCorrelationView instantiates a new CorrelationView and sets the default values.
func NewCorrelationView() *CorrelationView {
	m := &CorrelationView{}
	m.SetAdditionalData(make(map[string]any))
	return m
}

// CreateCorrelationViewFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateCorrelationViewFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) (i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
	return NewCorrelationView(), nil
}

// GetActivations gets the activations property value. The activations property
// returns a []NameCountable when successful
func (m *CorrelationView) GetActivations() []NameCountable {
	return m.activations
}

// GetAdditionalData gets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
// returns a map[string]any when successful
func (m *CorrelationView) GetAdditionalData() map[string]any {
	return m.additionalData
}

// GetArtifacts gets the artifacts property value. The artifacts property
// returns a []ArtifactRefable when successful
func (m *CorrelationView) GetArtifacts() []ArtifactRefable {
	return m.artifacts
}

// GetExperimentId gets the experiment_id property value. The experiment_id property
// returns a *UUID when successful
func (m *CorrelationView) GetExperimentId() *i561e97a8befe7661a44c8f54600992b4207a3a0cf6770e5559949bc276de2e22.UUID {
	return m.experiment_id
}

// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error when successful
func (m *CorrelationView) GetFieldDeserializers() map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
	res := make(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error)
	res["activations"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetCollectionOfObjectValues(CreateNameCountFromDiscriminatorValue)
		if err != nil {
			return err
		}
		if val != nil {
			res := make([]NameCountable, len(val))
			for i, v := range val {
				if v != nil {
					res[i] = v.(NameCountable)
				}
			}
			m.SetActivations(res)
		}
		return nil
	}
	res["artifacts"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetCollectionOfObjectValues(CreateArtifactRefFromDiscriminatorValue)
		if err != nil {
			return err
		}
		if val != nil {
			res := make([]ArtifactRefable, len(val))
			for i, v := range val {
				if v != nil {
					res[i] = v.(ArtifactRefable)
				}
			}
			m.SetArtifacts(res)
		}
		return nil
	}
	res["experiment_id"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetUUIDValue()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetExperimentId(val)
		}
		return nil
	}
	res["intents"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetCollectionOfObjectValues(CreateNameCountFromDiscriminatorValue)
		if err != nil {
			return err
		}
		if val != nil {
			res := make([]NameCountable, len(val))
			for i, v := range val {
				if v != nil {
					res[i] = v.(NameCountable)
				}
			}
			m.SetIntents(res)
		}
		return nil
	}
	res["name"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetStringValue()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetName(val)
		}
		return nil
	}
	res["observations"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetCollectionOfObjectValues(CreateNameCountFromDiscriminatorValue)
		if err != nil {
			return err
		}
		if val != nil {
			res := make([]NameCountable, len(val))
			for i, v := range val {
				if v != nil {
					res[i] = v.(NameCountable)
				}
			}
			m.SetObservations(res)
		}
		return nil
	}
	res["policy_decisions"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetCollectionOfObjectValues(CreateNameCountFromDiscriminatorValue)
		if err != nil {
			return err
		}
		if val != nil {
			res := make([]NameCountable, len(val))
			for i, v := range val {
				if v != nil {
					res[i] = v.(NameCountable)
				}
			}
			m.SetPolicyDecisions(res)
		}
		return nil
	}
	res["scenario"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetStringValue()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetScenario(val)
		}
		return nil
	}
	res["status"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetStringValue()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetStatus(val)
		}
		return nil
	}
	res["usage"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetObjectValue(CreateCorrelationUsageFromDiscriminatorValue)
		if err != nil {
			return err
		}
		if val != nil {
			m.SetUsage(val.(CorrelationUsageable))
		}
		return nil
	}
	return res
}

// GetIntents gets the intents property value. The intents property
// returns a []NameCountable when successful
func (m *CorrelationView) GetIntents() []NameCountable {
	return m.intents
}

// GetName gets the name property value. The name property
// returns a *string when successful
func (m *CorrelationView) GetName() *string {
	return m.name
}

// GetObservations gets the observations property value. The observations property
// returns a []NameCountable when successful
func (m *CorrelationView) GetObservations() []NameCountable {
	return m.observations
}

// GetPolicyDecisions gets the policy_decisions property value. The policy_decisions property
// returns a []NameCountable when successful
func (m *CorrelationView) GetPolicyDecisions() []NameCountable {
	return m.policy_decisions
}

// GetScenario gets the scenario property value. The scenario property
// returns a *string when successful
func (m *CorrelationView) GetScenario() *string {
	return m.scenario
}

// GetStatus gets the status property value. The status property
// returns a *string when successful
func (m *CorrelationView) GetStatus() *string {
	return m.status
}

// GetUsage gets the usage property value. The usage property
// returns a CorrelationUsageable when successful
func (m *CorrelationView) GetUsage() CorrelationUsageable {
	return m.usage
}

// Serialize serializes information the current object
func (m *CorrelationView) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter) error {
	if m.GetActivations() != nil {
		cast := make([]i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, len(m.GetActivations()))
		for i, v := range m.GetActivations() {
			if v != nil {
				cast[i] = v.(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable)
			}
		}
		err := writer.WriteCollectionOfObjectValues("activations", cast)
		if err != nil {
			return err
		}
	}
	if m.GetArtifacts() != nil {
		cast := make([]i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, len(m.GetArtifacts()))
		for i, v := range m.GetArtifacts() {
			if v != nil {
				cast[i] = v.(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable)
			}
		}
		err := writer.WriteCollectionOfObjectValues("artifacts", cast)
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteUUIDValue("experiment_id", m.GetExperimentId())
		if err != nil {
			return err
		}
	}
	if m.GetIntents() != nil {
		cast := make([]i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, len(m.GetIntents()))
		for i, v := range m.GetIntents() {
			if v != nil {
				cast[i] = v.(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable)
			}
		}
		err := writer.WriteCollectionOfObjectValues("intents", cast)
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteStringValue("name", m.GetName())
		if err != nil {
			return err
		}
	}
	if m.GetObservations() != nil {
		cast := make([]i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, len(m.GetObservations()))
		for i, v := range m.GetObservations() {
			if v != nil {
				cast[i] = v.(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable)
			}
		}
		err := writer.WriteCollectionOfObjectValues("observations", cast)
		if err != nil {
			return err
		}
	}
	if m.GetPolicyDecisions() != nil {
		cast := make([]i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, len(m.GetPolicyDecisions()))
		for i, v := range m.GetPolicyDecisions() {
			if v != nil {
				cast[i] = v.(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable)
			}
		}
		err := writer.WriteCollectionOfObjectValues("policy_decisions", cast)
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteStringValue("scenario", m.GetScenario())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteStringValue("status", m.GetStatus())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteObjectValue("usage", m.GetUsage())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteAdditionalData(m.GetAdditionalData())
		if err != nil {
			return err
		}
	}
	return nil
}

// SetActivations sets the activations property value. The activations property
func (m *CorrelationView) SetActivations(value []NameCountable) {
	m.activations = value
}

// SetAdditionalData sets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
func (m *CorrelationView) SetAdditionalData(value map[string]any) {
	m.additionalData = value
}

// SetArtifacts sets the artifacts property value. The artifacts property
func (m *CorrelationView) SetArtifacts(value []ArtifactRefable) {
	m.artifacts = value
}

// SetExperimentId sets the experiment_id property value. The experiment_id property
func (m *CorrelationView) SetExperimentId(value *i561e97a8befe7661a44c8f54600992b4207a3a0cf6770e5559949bc276de2e22.UUID) {
	m.experiment_id = value
}

// SetIntents sets the intents property value. The intents property
func (m *CorrelationView) SetIntents(value []NameCountable) {
	m.intents = value
}

// SetName sets the name property value. The name property
func (m *CorrelationView) SetName(value *string) {
	m.name = value
}

// SetObservations sets the observations property value. The observations property
func (m *CorrelationView) SetObservations(value []NameCountable) {
	m.observations = value
}

// SetPolicyDecisions sets the policy_decisions property value. The policy_decisions property
func (m *CorrelationView) SetPolicyDecisions(value []NameCountable) {
	m.policy_decisions = value
}

// SetScenario sets the scenario property value. The scenario property
func (m *CorrelationView) SetScenario(value *string) {
	m.scenario = value
}

// SetStatus sets the status property value. The status property
func (m *CorrelationView) SetStatus(value *string) {
	m.status = value
}

// SetUsage sets the usage property value. The usage property
func (m *CorrelationView) SetUsage(value CorrelationUsageable) {
	m.usage = value
}

type CorrelationViewable interface {
	i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.AdditionalDataHolder
	i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
	GetActivations() []NameCountable
	GetArtifacts() []ArtifactRefable
	GetExperimentId() *i561e97a8befe7661a44c8f54600992b4207a3a0cf6770e5559949bc276de2e22.UUID
	GetIntents() []NameCountable
	GetName() *string
	GetObservations() []NameCountable
	GetPolicyDecisions() []NameCountable
	GetScenario() *string
	GetStatus() *string
	GetUsage() CorrelationUsageable
	SetActivations(value []NameCountable)
	SetArtifacts(value []ArtifactRefable)
	SetExperimentId(value *i561e97a8befe7661a44c8f54600992b4207a3a0cf6770e5559949bc276de2e22.UUID)
	SetIntents(value []NameCountable)
	SetName(value *string)
	SetObservations(value []NameCountable)
	SetPolicyDecisions(value []NameCountable)
	SetScenario(value *string)
	SetStatus(value *string)
	SetUsage(value CorrelationUsageable)
}
