// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package models

import (
	i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

type CostReport struct {
	// Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
	additionalData map[string]any
	// The baseline property
	baseline CostLegable
	// The hours property
	hours *int64
	// The node_seconds_saved property
	node_seconds_saved *float64
	// The savings_pct property
	savings_pct *float64
	// The savings_usd property
	savings_usd *float64
	// The treatment property
	treatment CostLegable
	// The treatment_escalation_rate property
	treatment_escalation_rate *float64
	// The treatment_idle_time_s property
	treatment_idle_time_s *float64
	// The treatment_quality property
	treatment_quality CostQualityable
	// The treatment_release_latency_ms property
	treatment_release_latency_ms *float64
	// The variance property
	variance *string
}

// NewCostReport instantiates a new CostReport and sets the default values.
func NewCostReport() *CostReport {
	m := &CostReport{}
	m.SetAdditionalData(make(map[string]any))
	return m
}

// CreateCostReportFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateCostReportFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) (i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
	return NewCostReport(), nil
}

// GetAdditionalData gets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
// returns a map[string]any when successful
func (m *CostReport) GetAdditionalData() map[string]any {
	return m.additionalData
}

// GetBaseline gets the baseline property value. The baseline property
// returns a CostLegable when successful
func (m *CostReport) GetBaseline() CostLegable {
	return m.baseline
}

// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error when successful
func (m *CostReport) GetFieldDeserializers() map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
	res := make(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error)
	res["baseline"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetObjectValue(CreateCostLegFromDiscriminatorValue)
		if err != nil {
			return err
		}
		if val != nil {
			m.SetBaseline(val.(CostLegable))
		}
		return nil
	}
	res["hours"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetInt64Value()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetHours(val)
		}
		return nil
	}
	res["node_seconds_saved"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetFloat64Value()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetNodeSecondsSaved(val)
		}
		return nil
	}
	res["savings_pct"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetFloat64Value()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetSavingsPct(val)
		}
		return nil
	}
	res["savings_usd"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetFloat64Value()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetSavingsUsd(val)
		}
		return nil
	}
	res["treatment"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetObjectValue(CreateCostLegFromDiscriminatorValue)
		if err != nil {
			return err
		}
		if val != nil {
			m.SetTreatment(val.(CostLegable))
		}
		return nil
	}
	res["treatment_escalation_rate"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetFloat64Value()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetTreatmentEscalationRate(val)
		}
		return nil
	}
	res["treatment_idle_time_s"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetFloat64Value()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetTreatmentIdleTimeS(val)
		}
		return nil
	}
	res["treatment_quality"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetObjectValue(CreateCostQualityFromDiscriminatorValue)
		if err != nil {
			return err
		}
		if val != nil {
			m.SetTreatmentQuality(val.(CostQualityable))
		}
		return nil
	}
	res["treatment_release_latency_ms"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetFloat64Value()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetTreatmentReleaseLatencyMs(val)
		}
		return nil
	}
	res["variance"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetStringValue()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetVariance(val)
		}
		return nil
	}
	return res
}

// GetHours gets the hours property value. The hours property
// returns a *int64 when successful
func (m *CostReport) GetHours() *int64 {
	return m.hours
}

// GetNodeSecondsSaved gets the node_seconds_saved property value. The node_seconds_saved property
// returns a *float64 when successful
func (m *CostReport) GetNodeSecondsSaved() *float64 {
	return m.node_seconds_saved
}

// GetSavingsPct gets the savings_pct property value. The savings_pct property
// returns a *float64 when successful
func (m *CostReport) GetSavingsPct() *float64 {
	return m.savings_pct
}

// GetSavingsUsd gets the savings_usd property value. The savings_usd property
// returns a *float64 when successful
func (m *CostReport) GetSavingsUsd() *float64 {
	return m.savings_usd
}

// GetTreatment gets the treatment property value. The treatment property
// returns a CostLegable when successful
func (m *CostReport) GetTreatment() CostLegable {
	return m.treatment
}

// GetTreatmentEscalationRate gets the treatment_escalation_rate property value. The treatment_escalation_rate property
// returns a *float64 when successful
func (m *CostReport) GetTreatmentEscalationRate() *float64 {
	return m.treatment_escalation_rate
}

// GetTreatmentIdleTimeS gets the treatment_idle_time_s property value. The treatment_idle_time_s property
// returns a *float64 when successful
func (m *CostReport) GetTreatmentIdleTimeS() *float64 {
	return m.treatment_idle_time_s
}

// GetTreatmentQuality gets the treatment_quality property value. The treatment_quality property
// returns a CostQualityable when successful
func (m *CostReport) GetTreatmentQuality() CostQualityable {
	return m.treatment_quality
}

// GetTreatmentReleaseLatencyMs gets the treatment_release_latency_ms property value. The treatment_release_latency_ms property
// returns a *float64 when successful
func (m *CostReport) GetTreatmentReleaseLatencyMs() *float64 {
	return m.treatment_release_latency_ms
}

// GetVariance gets the variance property value. The variance property
// returns a *string when successful
func (m *CostReport) GetVariance() *string {
	return m.variance
}

// Serialize serializes information the current object
func (m *CostReport) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter) error {
	{
		err := writer.WriteObjectValue("baseline", m.GetBaseline())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteInt64Value("hours", m.GetHours())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteFloat64Value("node_seconds_saved", m.GetNodeSecondsSaved())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteFloat64Value("savings_pct", m.GetSavingsPct())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteFloat64Value("savings_usd", m.GetSavingsUsd())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteObjectValue("treatment", m.GetTreatment())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteFloat64Value("treatment_escalation_rate", m.GetTreatmentEscalationRate())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteFloat64Value("treatment_idle_time_s", m.GetTreatmentIdleTimeS())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteObjectValue("treatment_quality", m.GetTreatmentQuality())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteFloat64Value("treatment_release_latency_ms", m.GetTreatmentReleaseLatencyMs())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteStringValue("variance", m.GetVariance())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteAdditionalData(m.GetAdditionalData())
		if err != nil {
			return err
		}
	}
	return nil
}

// SetAdditionalData sets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
func (m *CostReport) SetAdditionalData(value map[string]any) {
	m.additionalData = value
}

// SetBaseline sets the baseline property value. The baseline property
func (m *CostReport) SetBaseline(value CostLegable) {
	m.baseline = value
}

// SetHours sets the hours property value. The hours property
func (m *CostReport) SetHours(value *int64) {
	m.hours = value
}

// SetNodeSecondsSaved sets the node_seconds_saved property value. The node_seconds_saved property
func (m *CostReport) SetNodeSecondsSaved(value *float64) {
	m.node_seconds_saved = value
}

// SetSavingsPct sets the savings_pct property value. The savings_pct property
func (m *CostReport) SetSavingsPct(value *float64) {
	m.savings_pct = value
}

// SetSavingsUsd sets the savings_usd property value. The savings_usd property
func (m *CostReport) SetSavingsUsd(value *float64) {
	m.savings_usd = value
}

// SetTreatment sets the treatment property value. The treatment property
func (m *CostReport) SetTreatment(value CostLegable) {
	m.treatment = value
}

// SetTreatmentEscalationRate sets the treatment_escalation_rate property value. The treatment_escalation_rate property
func (m *CostReport) SetTreatmentEscalationRate(value *float64) {
	m.treatment_escalation_rate = value
}

// SetTreatmentIdleTimeS sets the treatment_idle_time_s property value. The treatment_idle_time_s property
func (m *CostReport) SetTreatmentIdleTimeS(value *float64) {
	m.treatment_idle_time_s = value
}

// SetTreatmentQuality sets the treatment_quality property value. The treatment_quality property
func (m *CostReport) SetTreatmentQuality(value CostQualityable) {
	m.treatment_quality = value
}

// SetTreatmentReleaseLatencyMs sets the treatment_release_latency_ms property value. The treatment_release_latency_ms property
func (m *CostReport) SetTreatmentReleaseLatencyMs(value *float64) {
	m.treatment_release_latency_ms = value
}

// SetVariance sets the variance property value. The variance property
func (m *CostReport) SetVariance(value *string) {
	m.variance = value
}

type CostReportable interface {
	i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.AdditionalDataHolder
	i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
	GetBaseline() CostLegable
	GetHours() *int64
	GetNodeSecondsSaved() *float64
	GetSavingsPct() *float64
	GetSavingsUsd() *float64
	GetTreatment() CostLegable
	GetTreatmentEscalationRate() *float64
	GetTreatmentIdleTimeS() *float64
	GetTreatmentQuality() CostQualityable
	GetTreatmentReleaseLatencyMs() *float64
	GetVariance() *string
	SetBaseline(value CostLegable)
	SetHours(value *int64)
	SetNodeSecondsSaved(value *float64)
	SetSavingsPct(value *float64)
	SetSavingsUsd(value *float64)
	SetTreatment(value CostLegable)
	SetTreatmentEscalationRate(value *float64)
	SetTreatmentIdleTimeS(value *float64)
	SetTreatmentQuality(value CostQualityable)
	SetTreatmentReleaseLatencyMs(value *float64)
	SetVariance(value *string)
}
