// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package models

import (
	i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// DynamoMetricsIngestRequest batch of metric samples posted by the watcher after scraping /metrics.
type DynamoMetricsIngestRequest struct {
	// Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
	additionalData map[string]any
	// The cluster_id property
	cluster_id *string
	// The model property
	model *string
	// The namespace property
	namespace *string
	// The samples property
	samples []DynamoMetricSampleable
}

// NewDynamoMetricsIngestRequest instantiates a new DynamoMetricsIngestRequest and sets the default values.
func NewDynamoMetricsIngestRequest() *DynamoMetricsIngestRequest {
	m := &DynamoMetricsIngestRequest{}
	m.SetAdditionalData(make(map[string]any))
	return m
}

// CreateDynamoMetricsIngestRequestFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateDynamoMetricsIngestRequestFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) (i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
	return NewDynamoMetricsIngestRequest(), nil
}

// GetAdditionalData gets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
// returns a map[string]any when successful
func (m *DynamoMetricsIngestRequest) GetAdditionalData() map[string]any {
	return m.additionalData
}

// GetClusterId gets the cluster_id property value. The cluster_id property
// returns a *string when successful
func (m *DynamoMetricsIngestRequest) GetClusterId() *string {
	return m.cluster_id
}

// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error when successful
func (m *DynamoMetricsIngestRequest) GetFieldDeserializers() map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
	res := make(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error)
	res["cluster_id"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetStringValue()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetClusterId(val)
		}
		return nil
	}
	res["model"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetStringValue()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetModel(val)
		}
		return nil
	}
	res["namespace"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetStringValue()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetNamespace(val)
		}
		return nil
	}
	res["samples"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetCollectionOfObjectValues(CreateDynamoMetricSampleFromDiscriminatorValue)
		if err != nil {
			return err
		}
		if val != nil {
			res := make([]DynamoMetricSampleable, len(val))
			for i, v := range val {
				if v != nil {
					res[i] = v.(DynamoMetricSampleable)
				}
			}
			m.SetSamples(res)
		}
		return nil
	}
	return res
}

// GetModel gets the model property value. The model property
// returns a *string when successful
func (m *DynamoMetricsIngestRequest) GetModel() *string {
	return m.model
}

// GetNamespace gets the namespace property value. The namespace property
// returns a *string when successful
func (m *DynamoMetricsIngestRequest) GetNamespace() *string {
	return m.namespace
}

// GetSamples gets the samples property value. The samples property
// returns a []DynamoMetricSampleable when successful
func (m *DynamoMetricsIngestRequest) GetSamples() []DynamoMetricSampleable {
	return m.samples
}

// Serialize serializes information the current object
func (m *DynamoMetricsIngestRequest) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter) error {
	{
		err := writer.WriteStringValue("cluster_id", m.GetClusterId())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteStringValue("model", m.GetModel())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteStringValue("namespace", m.GetNamespace())
		if err != nil {
			return err
		}
	}
	if m.GetSamples() != nil {
		cast := make([]i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, len(m.GetSamples()))
		for i, v := range m.GetSamples() {
			if v != nil {
				cast[i] = v.(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable)
			}
		}
		err := writer.WriteCollectionOfObjectValues("samples", cast)
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteAdditionalData(m.GetAdditionalData())
		if err != nil {
			return err
		}
	}
	return nil
}

// SetAdditionalData sets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
func (m *DynamoMetricsIngestRequest) SetAdditionalData(value map[string]any) {
	m.additionalData = value
}

// SetClusterId sets the cluster_id property value. The cluster_id property
func (m *DynamoMetricsIngestRequest) SetClusterId(value *string) {
	m.cluster_id = value
}

// SetModel sets the model property value. The model property
func (m *DynamoMetricsIngestRequest) SetModel(value *string) {
	m.model = value
}

// SetNamespace sets the namespace property value. The namespace property
func (m *DynamoMetricsIngestRequest) SetNamespace(value *string) {
	m.namespace = value
}

// SetSamples sets the samples property value. The samples property
func (m *DynamoMetricsIngestRequest) SetSamples(value []DynamoMetricSampleable) {
	m.samples = value
}

type DynamoMetricsIngestRequestable interface {
	i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.AdditionalDataHolder
	i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
	GetClusterId() *string
	GetModel() *string
	GetNamespace() *string
	GetSamples() []DynamoMetricSampleable
	SetClusterId(value *string)
	SetModel(value *string)
	SetNamespace(value *string)
	SetSamples(value []DynamoMetricSampleable)
}
