// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package models

import (
	i561e97a8befe7661a44c8f54600992b4207a3a0cf6770e5559949bc276de2e22 "github.com/google/uuid"
	i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

type RestoreProfileUploadResponse struct {
	// Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
	additionalData map[string]any
	// The profile_object_path property
	profile_object_path *string
	// The restore_uuid property
	restore_uuid *i561e97a8befe7661a44c8f54600992b4207a3a0cf6770e5559949bc276de2e22.UUID
}

// NewRestoreProfileUploadResponse instantiates a new RestoreProfileUploadResponse and sets the default values.
func NewRestoreProfileUploadResponse() *RestoreProfileUploadResponse {
	m := &RestoreProfileUploadResponse{}
	m.SetAdditionalData(make(map[string]any))
	return m
}

// CreateRestoreProfileUploadResponseFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateRestoreProfileUploadResponseFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) (i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
	return NewRestoreProfileUploadResponse(), nil
}

// GetAdditionalData gets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
// returns a map[string]any when successful
func (m *RestoreProfileUploadResponse) GetAdditionalData() map[string]any {
	return m.additionalData
}

// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error when successful
func (m *RestoreProfileUploadResponse) GetFieldDeserializers() map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
	res := make(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error)
	res["profile_object_path"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetStringValue()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetProfileObjectPath(val)
		}
		return nil
	}
	res["restore_uuid"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetUUIDValue()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetRestoreUuid(val)
		}
		return nil
	}
	return res
}

// GetProfileObjectPath gets the profile_object_path property value. The profile_object_path property
// returns a *string when successful
func (m *RestoreProfileUploadResponse) GetProfileObjectPath() *string {
	return m.profile_object_path
}

// GetRestoreUuid gets the restore_uuid property value. The restore_uuid property
// returns a *UUID when successful
func (m *RestoreProfileUploadResponse) GetRestoreUuid() *i561e97a8befe7661a44c8f54600992b4207a3a0cf6770e5559949bc276de2e22.UUID {
	return m.restore_uuid
}

// Serialize serializes information the current object
func (m *RestoreProfileUploadResponse) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter) error {
	{
		err := writer.WriteStringValue("profile_object_path", m.GetProfileObjectPath())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteUUIDValue("restore_uuid", m.GetRestoreUuid())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteAdditionalData(m.GetAdditionalData())
		if err != nil {
			return err
		}
	}
	return nil
}

// SetAdditionalData sets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
func (m *RestoreProfileUploadResponse) SetAdditionalData(value map[string]any) {
	m.additionalData = value
}

// SetProfileObjectPath sets the profile_object_path property value. The profile_object_path property
func (m *RestoreProfileUploadResponse) SetProfileObjectPath(value *string) {
	m.profile_object_path = value
}

// SetRestoreUuid sets the restore_uuid property value. The restore_uuid property
func (m *RestoreProfileUploadResponse) SetRestoreUuid(value *i561e97a8befe7661a44c8f54600992b4207a3a0cf6770e5559949bc276de2e22.UUID) {
	m.restore_uuid = value
}

type RestoreProfileUploadResponseable interface {
	i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.AdditionalDataHolder
	i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
	GetProfileObjectPath() *string
	GetRestoreUuid() *i561e97a8befe7661a44c8f54600992b4207a3a0cf6770e5559949bc276de2e22.UUID
	SetProfileObjectPath(value *string)
	SetRestoreUuid(value *i561e97a8befe7661a44c8f54600992b4207a3a0cf6770e5559949bc276de2e22.UUID)
}
