// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package models

import (
	i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// UpsertInstanceTypePricingRequest request to create or update instance type pricing
type UpsertInstanceTypePricingRequest struct {
	// Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
	additionalData map[string]any
	// "spot" or "on-demand"
	capacity_type *string
	// The instance_type property
	instance_type *string
	// Hourly cost when running as on-demand
	ondemand_price_per_hour *float64
	// Hourly cost when running as spot
	spot_price_per_hour *float64
}

// NewUpsertInstanceTypePricingRequest instantiates a new UpsertInstanceTypePricingRequest and sets the default values.
func NewUpsertInstanceTypePricingRequest() *UpsertInstanceTypePricingRequest {
	m := &UpsertInstanceTypePricingRequest{}
	m.SetAdditionalData(make(map[string]any))
	return m
}

// CreateUpsertInstanceTypePricingRequestFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateUpsertInstanceTypePricingRequestFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) (i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
	return NewUpsertInstanceTypePricingRequest(), nil
}

// GetAdditionalData gets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
// returns a map[string]any when successful
func (m *UpsertInstanceTypePricingRequest) GetAdditionalData() map[string]any {
	return m.additionalData
}

// GetCapacityType gets the capacity_type property value. "spot" or "on-demand"
// returns a *string when successful
func (m *UpsertInstanceTypePricingRequest) GetCapacityType() *string {
	return m.capacity_type
}

// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error when successful
func (m *UpsertInstanceTypePricingRequest) GetFieldDeserializers() map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
	res := make(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error)
	res["capacity_type"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetStringValue()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetCapacityType(val)
		}
		return nil
	}
	res["instance_type"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetStringValue()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetInstanceType(val)
		}
		return nil
	}
	res["ondemand_price_per_hour"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetFloat64Value()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetOndemandPricePerHour(val)
		}
		return nil
	}
	res["spot_price_per_hour"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetFloat64Value()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetSpotPricePerHour(val)
		}
		return nil
	}
	return res
}

// GetInstanceType gets the instance_type property value. The instance_type property
// returns a *string when successful
func (m *UpsertInstanceTypePricingRequest) GetInstanceType() *string {
	return m.instance_type
}

// GetOndemandPricePerHour gets the ondemand_price_per_hour property value. Hourly cost when running as on-demand
// returns a *float64 when successful
func (m *UpsertInstanceTypePricingRequest) GetOndemandPricePerHour() *float64 {
	return m.ondemand_price_per_hour
}

// GetSpotPricePerHour gets the spot_price_per_hour property value. Hourly cost when running as spot
// returns a *float64 when successful
func (m *UpsertInstanceTypePricingRequest) GetSpotPricePerHour() *float64 {
	return m.spot_price_per_hour
}

// Serialize serializes information the current object
func (m *UpsertInstanceTypePricingRequest) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter) error {
	{
		err := writer.WriteStringValue("capacity_type", m.GetCapacityType())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteStringValue("instance_type", m.GetInstanceType())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteFloat64Value("ondemand_price_per_hour", m.GetOndemandPricePerHour())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteFloat64Value("spot_price_per_hour", m.GetSpotPricePerHour())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteAdditionalData(m.GetAdditionalData())
		if err != nil {
			return err
		}
	}
	return nil
}

// SetAdditionalData sets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
func (m *UpsertInstanceTypePricingRequest) SetAdditionalData(value map[string]any) {
	m.additionalData = value
}

// SetCapacityType sets the capacity_type property value. "spot" or "on-demand"
func (m *UpsertInstanceTypePricingRequest) SetCapacityType(value *string) {
	m.capacity_type = value
}

// SetInstanceType sets the instance_type property value. The instance_type property
func (m *UpsertInstanceTypePricingRequest) SetInstanceType(value *string) {
	m.instance_type = value
}

// SetOndemandPricePerHour sets the ondemand_price_per_hour property value. Hourly cost when running as on-demand
func (m *UpsertInstanceTypePricingRequest) SetOndemandPricePerHour(value *float64) {
	m.ondemand_price_per_hour = value
}

// SetSpotPricePerHour sets the spot_price_per_hour property value. Hourly cost when running as spot
func (m *UpsertInstanceTypePricingRequest) SetSpotPricePerHour(value *float64) {
	m.spot_price_per_hour = value
}

type UpsertInstanceTypePricingRequestable interface {
	i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.AdditionalDataHolder
	i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
	GetCapacityType() *string
	GetInstanceType() *string
	GetOndemandPricePerHour() *float64
	GetSpotPricePerHour() *float64
	SetCapacityType(value *string)
	SetInstanceType(value *string)
	SetOndemandPricePerHour(value *float64)
	SetSpotPricePerHour(value *float64)
}
