// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package v1

import (
	"context"
	i89856fb30cc728ac649e5f2184f35b3dbca9c394c0e717f9e3ad3070b5506e89 "github.com/cedana/cedana-propagator-sdk/go/models"
	i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f "github.com/microsoft/kiota-abstractions-go"
)

// DownloadRequestBuilder builds and executes requests for operations under \v1\download
type DownloadRequestBuilder struct {
	i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.BaseRequestBuilder
}

// DownloadRequestBuilderGetQueryParameters download the cedana binary.
type DownloadRequestBuilderGetQueryParameters struct {
	// Architecture, e.g. amd64
	Arch *string "uriparametername:\"arch\""
	// Build type: alpha|release
	Build *string "uriparametername:\"build\""
	// set to true to fetch with exact repository name and build name
	Exact *string "uriparametername:\"exact\""
	// Exact version match, e.g. 0.9.2
	Version *string "uriparametername:\"version\""
}

// DownloadRequestBuilderGetRequestConfiguration configuration for the request such as headers, query parameters, and middleware options.
type DownloadRequestBuilderGetRequestConfiguration struct {
	// Request headers
	Headers *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestHeaders
	// Request options
	Options []i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestOption
	// Request query parameters
	QueryParameters *DownloadRequestBuilderGetQueryParameters
}

// NewDownloadRequestBuilderInternal instantiates a new DownloadRequestBuilder and sets the default values.
func NewDownloadRequestBuilderInternal(pathParameters map[string]string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter) *DownloadRequestBuilder {
	m := &DownloadRequestBuilder{
		BaseRequestBuilder: *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewBaseRequestBuilder(requestAdapter, "{+baseurl}/v1/download{?arch*,build*,exact*,version*}", pathParameters),
	}
	return m
}

// NewDownloadRequestBuilder instantiates a new DownloadRequestBuilder and sets the default values.
func NewDownloadRequestBuilder(rawUrl string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter) *DownloadRequestBuilder {
	urlParams := make(map[string]string)
	urlParams["request-raw-url"] = rawUrl
	return NewDownloadRequestBuilderInternal(urlParams, requestAdapter)
}

// Get download the cedana binary.
// returns a HttpError error when the service returns a 400 status code
// returns a HttpError error when the service returns a 404 status code
// returns a HttpError error when the service returns a 500 status code
// returns a HttpError error when the service returns a 4XX or 5XX status code
func (m *DownloadRequestBuilder) Get(ctx context.Context, requestConfiguration *DownloadRequestBuilderGetRequestConfiguration) error {
	requestInfo, err := m.ToGetRequestInformation(ctx, requestConfiguration)
	if err != nil {
		return err
	}
	errorMapping := i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.ErrorMappings{
		"400": i89856fb30cc728ac649e5f2184f35b3dbca9c394c0e717f9e3ad3070b5506e89.CreateHttpErrorFromDiscriminatorValue,
		"404": i89856fb30cc728ac649e5f2184f35b3dbca9c394c0e717f9e3ad3070b5506e89.CreateHttpErrorFromDiscriminatorValue,
		"500": i89856fb30cc728ac649e5f2184f35b3dbca9c394c0e717f9e3ad3070b5506e89.CreateHttpErrorFromDiscriminatorValue,
		"XXX": i89856fb30cc728ac649e5f2184f35b3dbca9c394c0e717f9e3ad3070b5506e89.CreateHttpErrorFromDiscriminatorValue,
	}
	err = m.BaseRequestBuilder.RequestAdapter.SendNoContent(ctx, requestInfo, errorMapping)
	if err != nil {
		return err
	}
	return nil
}

// ToGetRequestInformation download the cedana binary.
// returns a *RequestInformation when successful
func (m *DownloadRequestBuilder) ToGetRequestInformation(ctx context.Context, requestConfiguration *DownloadRequestBuilderGetRequestConfiguration) (*i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestInformation, error) {
	requestInfo := i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewRequestInformationWithMethodAndUrlTemplateAndPathParameters(i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.GET, m.BaseRequestBuilder.UrlTemplate, m.BaseRequestBuilder.PathParameters)
	if requestConfiguration != nil {
		if requestConfiguration.QueryParameters != nil {
			requestInfo.AddQueryParameters(*(requestConfiguration.QueryParameters))
		}
		requestInfo.Headers.AddAll(requestConfiguration.Headers)
		requestInfo.AddRequestOptions(requestConfiguration.Options)
	}
	requestInfo.Headers.TryAdd("Accept", "application/json")
	return requestInfo, nil
}

// WithUrl returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
// returns a *DownloadRequestBuilder when successful
func (m *DownloadRequestBuilder) WithUrl(rawUrl string) *DownloadRequestBuilder {
	return NewDownloadRequestBuilder(rawUrl, m.BaseRequestBuilder.RequestAdapter)
}
