// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package models

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

type AvailableFilters struct {
    // Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
    additionalData map[string]any
    // The namespaces property
    namespaces []string
    // The statuses property
    statuses []string
}
// NewAvailableFilters instantiates a new AvailableFilters and sets the default values.
func NewAvailableFilters()(*AvailableFilters) {
    m := &AvailableFilters{
    }
    m.SetAdditionalData(make(map[string]any))
    return m
}
// CreateAvailableFiltersFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateAvailableFiltersFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewAvailableFilters(), nil
}
// GetAdditionalData gets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
// returns a map[string]any when successful
func (m *AvailableFilters) GetAdditionalData()(map[string]any) {
    return m.additionalData
}
// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error) when successful
func (m *AvailableFilters) GetFieldDeserializers()(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error)) {
    res := make(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error))
    res["namespaces"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetCollectionOfPrimitiveValues("string")
        if err != nil {
            return err
        }
        if val != nil {
            res := make([]string, len(val))
            for i, v := range val {
                if v != nil {
                    res[i] = *(v.(*string))
                }
            }
            m.SetNamespaces(res)
        }
        return nil
    }
    res["statuses"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetCollectionOfPrimitiveValues("string")
        if err != nil {
            return err
        }
        if val != nil {
            res := make([]string, len(val))
            for i, v := range val {
                if v != nil {
                    res[i] = *(v.(*string))
                }
            }
            m.SetStatuses(res)
        }
        return nil
    }
    return res
}
// GetNamespaces gets the namespaces property value. The namespaces property
// returns a []string when successful
func (m *AvailableFilters) GetNamespaces()([]string) {
    return m.namespaces
}
// GetStatuses gets the statuses property value. The statuses property
// returns a []string when successful
func (m *AvailableFilters) GetStatuses()([]string) {
    return m.statuses
}
// Serialize serializes information the current object
func (m *AvailableFilters) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter)(error) {
    if m.GetNamespaces() != nil {
        err := writer.WriteCollectionOfStringValues("namespaces", m.GetNamespaces())
        if err != nil {
            return err
        }
    }
    if m.GetStatuses() != nil {
        err := writer.WriteCollectionOfStringValues("statuses", m.GetStatuses())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteAdditionalData(m.GetAdditionalData())
        if err != nil {
            return err
        }
    }
    return nil
}
// SetAdditionalData sets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
func (m *AvailableFilters) SetAdditionalData(value map[string]any)() {
    m.additionalData = value
}
// SetNamespaces sets the namespaces property value. The namespaces property
func (m *AvailableFilters) SetNamespaces(value []string)() {
    m.namespaces = value
}
// SetStatuses sets the statuses property value. The statuses property
func (m *AvailableFilters) SetStatuses(value []string)() {
    m.statuses = value
}
type AvailableFiltersable interface {
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.AdditionalDataHolder
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
    GetNamespaces()([]string)
    GetStatuses()([]string)
    SetNamespaces(value []string)()
    SetStatuses(value []string)()
}
