// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package models

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

type BurstingStatus struct {
    // Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
    additionalData map[string]any
    // The can_use_bursting property
    can_use_bursting *bool
    // The message property
    message *string
    // The status property
    status *BurstingConfigStatus
}
// NewBurstingStatus instantiates a new BurstingStatus and sets the default values.
func NewBurstingStatus()(*BurstingStatus) {
    m := &BurstingStatus{
    }
    m.SetAdditionalData(make(map[string]any))
    return m
}
// CreateBurstingStatusFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateBurstingStatusFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewBurstingStatus(), nil
}
// GetAdditionalData gets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
// returns a map[string]any when successful
func (m *BurstingStatus) GetAdditionalData()(map[string]any) {
    return m.additionalData
}
// GetCanUseBursting gets the can_use_bursting property value. The can_use_bursting property
// returns a *bool when successful
func (m *BurstingStatus) GetCanUseBursting()(*bool) {
    return m.can_use_bursting
}
// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error) when successful
func (m *BurstingStatus) GetFieldDeserializers()(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error)) {
    res := make(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error))
    res["can_use_bursting"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetBoolValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetCanUseBursting(val)
        }
        return nil
    }
    res["message"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetMessage(val)
        }
        return nil
    }
    res["status"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetEnumValue(ParseBurstingConfigStatus)
        if err != nil {
            return err
        }
        if val != nil {
            m.SetStatus(val.(*BurstingConfigStatus))
        }
        return nil
    }
    return res
}
// GetMessage gets the message property value. The message property
// returns a *string when successful
func (m *BurstingStatus) GetMessage()(*string) {
    return m.message
}
// GetStatus gets the status property value. The status property
// returns a *BurstingConfigStatus when successful
func (m *BurstingStatus) GetStatus()(*BurstingConfigStatus) {
    return m.status
}
// Serialize serializes information the current object
func (m *BurstingStatus) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter)(error) {
    {
        err := writer.WriteBoolValue("can_use_bursting", m.GetCanUseBursting())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("message", m.GetMessage())
        if err != nil {
            return err
        }
    }
    if m.GetStatus() != nil {
        cast := (*m.GetStatus()).String()
        err := writer.WriteStringValue("status", &cast)
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteAdditionalData(m.GetAdditionalData())
        if err != nil {
            return err
        }
    }
    return nil
}
// SetAdditionalData sets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
func (m *BurstingStatus) SetAdditionalData(value map[string]any)() {
    m.additionalData = value
}
// SetCanUseBursting sets the can_use_bursting property value. The can_use_bursting property
func (m *BurstingStatus) SetCanUseBursting(value *bool)() {
    m.can_use_bursting = value
}
// SetMessage sets the message property value. The message property
func (m *BurstingStatus) SetMessage(value *string)() {
    m.message = value
}
// SetStatus sets the status property value. The status property
func (m *BurstingStatus) SetStatus(value *BurstingConfigStatus)() {
    m.status = value
}
type BurstingStatusable interface {
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.AdditionalDataHolder
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
    GetCanUseBursting()(*bool)
    GetMessage()(*string)
    GetStatus()(*BurstingConfigStatus)
    SetCanUseBursting(value *bool)()
    SetMessage(value *string)()
    SetStatus(value *BurstingConfigStatus)()
}
