// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package models

import (
	i561e97a8befe7661a44c8f54600992b4207a3a0cf6770e5559949bc276de2e22 "github.com/google/uuid"
	i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
	i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e "time"
)

// CheckpointRequestView an on-demand checkpoint request and how far it has got.
type CheckpointRequestView struct {
	// Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
	additionalData map[string]any
	// The artifact the checkpoint produced, once it succeeded.
	artifact_id *string
	// The completed_at property
	completed_at *i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time
	// Why it failed, in the controller's words.
	error *string
	// checkpoint or restart. One row per profile, so asking twice returns the open one.
	kind *string
	// The profile_id property
	profile_id *string
	// The reason property
	reason *string
	// The replace_existing property
	replace_existing *bool
	// Identifies this attempt. A caller polling with the id it was givencannot be shown a later request's outcome as though it were its own.
	request_id *i561e97a8befe7661a44c8f54600992b4207a3a0cf6770e5559949bc276de2e22.UUID
	// The requested_at property
	requested_at *i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time
	// The started_at property
	started_at *i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time
	// pending → running → succeeded | failed
	status *string
}

// NewCheckpointRequestView instantiates a new CheckpointRequestView and sets the default values.
func NewCheckpointRequestView() *CheckpointRequestView {
	m := &CheckpointRequestView{}
	m.SetAdditionalData(make(map[string]any))
	return m
}

// CreateCheckpointRequestViewFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateCheckpointRequestViewFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) (i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
	return NewCheckpointRequestView(), nil
}

// GetAdditionalData gets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
// returns a map[string]any when successful
func (m *CheckpointRequestView) GetAdditionalData() map[string]any {
	return m.additionalData
}

// GetArtifactId gets the artifact_id property value. The artifact the checkpoint produced, once it succeeded.
// returns a *string when successful
func (m *CheckpointRequestView) GetArtifactId() *string {
	return m.artifact_id
}

// GetCompletedAt gets the completed_at property value. The completed_at property
// returns a *Time when successful
func (m *CheckpointRequestView) GetCompletedAt() *i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time {
	return m.completed_at
}

// GetError gets the error property value. Why it failed, in the controller's words.
// returns a *string when successful
func (m *CheckpointRequestView) GetError() *string {
	return m.error
}

// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error when successful
func (m *CheckpointRequestView) GetFieldDeserializers() map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
	res := make(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error)
	res["artifact_id"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetStringValue()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetArtifactId(val)
		}
		return nil
	}
	res["completed_at"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetTimeValue()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetCompletedAt(val)
		}
		return nil
	}
	res["error"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetStringValue()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetError(val)
		}
		return nil
	}
	res["kind"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetStringValue()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetKind(val)
		}
		return nil
	}
	res["profile_id"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetStringValue()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetProfileId(val)
		}
		return nil
	}
	res["reason"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetStringValue()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetReason(val)
		}
		return nil
	}
	res["replace_existing"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetBoolValue()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetReplaceExisting(val)
		}
		return nil
	}
	res["request_id"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetUUIDValue()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetRequestId(val)
		}
		return nil
	}
	res["requested_at"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetTimeValue()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetRequestedAt(val)
		}
		return nil
	}
	res["started_at"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetTimeValue()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetStartedAt(val)
		}
		return nil
	}
	res["status"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetStringValue()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetStatus(val)
		}
		return nil
	}
	return res
}

// GetKind gets the kind property value. checkpoint or restart. One row per profile, so asking twice returns the open one.
// returns a *string when successful
func (m *CheckpointRequestView) GetKind() *string {
	return m.kind
}

// GetProfileId gets the profile_id property value. The profile_id property
// returns a *string when successful
func (m *CheckpointRequestView) GetProfileId() *string {
	return m.profile_id
}

// GetReason gets the reason property value. The reason property
// returns a *string when successful
func (m *CheckpointRequestView) GetReason() *string {
	return m.reason
}

// GetReplaceExisting gets the replace_existing property value. The replace_existing property
// returns a *bool when successful
func (m *CheckpointRequestView) GetReplaceExisting() *bool {
	return m.replace_existing
}

// GetRequestedAt gets the requested_at property value. The requested_at property
// returns a *Time when successful
func (m *CheckpointRequestView) GetRequestedAt() *i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time {
	return m.requested_at
}

// GetRequestId gets the request_id property value. Identifies this attempt. A caller polling with the id it was givencannot be shown a later request's outcome as though it were its own.
// returns a *UUID when successful
func (m *CheckpointRequestView) GetRequestId() *i561e97a8befe7661a44c8f54600992b4207a3a0cf6770e5559949bc276de2e22.UUID {
	return m.request_id
}

// GetStartedAt gets the started_at property value. The started_at property
// returns a *Time when successful
func (m *CheckpointRequestView) GetStartedAt() *i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time {
	return m.started_at
}

// GetStatus gets the status property value. pending → running → succeeded | failed
// returns a *string when successful
func (m *CheckpointRequestView) GetStatus() *string {
	return m.status
}

// Serialize serializes information the current object
func (m *CheckpointRequestView) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter) error {
	{
		err := writer.WriteStringValue("artifact_id", m.GetArtifactId())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteTimeValue("completed_at", m.GetCompletedAt())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteStringValue("error", m.GetError())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteStringValue("kind", m.GetKind())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteStringValue("profile_id", m.GetProfileId())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteStringValue("reason", m.GetReason())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteBoolValue("replace_existing", m.GetReplaceExisting())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteTimeValue("requested_at", m.GetRequestedAt())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteUUIDValue("request_id", m.GetRequestId())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteTimeValue("started_at", m.GetStartedAt())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteStringValue("status", m.GetStatus())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteAdditionalData(m.GetAdditionalData())
		if err != nil {
			return err
		}
	}
	return nil
}

// SetAdditionalData sets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
func (m *CheckpointRequestView) SetAdditionalData(value map[string]any) {
	m.additionalData = value
}

// SetArtifactId sets the artifact_id property value. The artifact the checkpoint produced, once it succeeded.
func (m *CheckpointRequestView) SetArtifactId(value *string) {
	m.artifact_id = value
}

// SetCompletedAt sets the completed_at property value. The completed_at property
func (m *CheckpointRequestView) SetCompletedAt(value *i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time) {
	m.completed_at = value
}

// SetError sets the error property value. Why it failed, in the controller's words.
func (m *CheckpointRequestView) SetError(value *string) {
	m.error = value
}

// SetKind sets the kind property value. checkpoint or restart. One row per profile, so asking twice returns the open one.
func (m *CheckpointRequestView) SetKind(value *string) {
	m.kind = value
}

// SetProfileId sets the profile_id property value. The profile_id property
func (m *CheckpointRequestView) SetProfileId(value *string) {
	m.profile_id = value
}

// SetReason sets the reason property value. The reason property
func (m *CheckpointRequestView) SetReason(value *string) {
	m.reason = value
}

// SetReplaceExisting sets the replace_existing property value. The replace_existing property
func (m *CheckpointRequestView) SetReplaceExisting(value *bool) {
	m.replace_existing = value
}

// SetRequestedAt sets the requested_at property value. The requested_at property
func (m *CheckpointRequestView) SetRequestedAt(value *i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time) {
	m.requested_at = value
}

// SetRequestId sets the request_id property value. Identifies this attempt. A caller polling with the id it was givencannot be shown a later request's outcome as though it were its own.
func (m *CheckpointRequestView) SetRequestId(value *i561e97a8befe7661a44c8f54600992b4207a3a0cf6770e5559949bc276de2e22.UUID) {
	m.request_id = value
}

// SetStartedAt sets the started_at property value. The started_at property
func (m *CheckpointRequestView) SetStartedAt(value *i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time) {
	m.started_at = value
}

// SetStatus sets the status property value. pending → running → succeeded | failed
func (m *CheckpointRequestView) SetStatus(value *string) {
	m.status = value
}

type CheckpointRequestViewable interface {
	i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.AdditionalDataHolder
	i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
	GetArtifactId() *string
	GetCompletedAt() *i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time
	GetError() *string
	GetKind() *string
	GetProfileId() *string
	GetReason() *string
	GetReplaceExisting() *bool
	GetRequestedAt() *i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time
	GetRequestId() *i561e97a8befe7661a44c8f54600992b4207a3a0cf6770e5559949bc276de2e22.UUID
	GetStartedAt() *i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time
	GetStatus() *string
	SetArtifactId(value *string)
	SetCompletedAt(value *i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time)
	SetError(value *string)
	SetKind(value *string)
	SetProfileId(value *string)
	SetReason(value *string)
	SetReplaceExisting(value *bool)
	SetRequestedAt(value *i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time)
	SetRequestId(value *i561e97a8befe7661a44c8f54600992b4207a3a0cf6770e5559949bc276de2e22.UUID)
	SetStartedAt(value *i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time)
	SetStatus(value *string)
}
