// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package models

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

type CheckpointPod struct {
    // The action_id property
    action_id *string
    // Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
    additionalData map[string]any
    // The cluster_id property
    cluster_id *string
    // The kind property
    kind *CheckpointKind
    // The namespace property
    namespace *string
    // The pod_id property
    pod_id *string
    // The pod_name property
    pod_name *string
    // The runc_root property
    runc_root *string
}
// NewCheckpointPod instantiates a new CheckpointPod and sets the default values.
func NewCheckpointPod()(*CheckpointPod) {
    m := &CheckpointPod{
    }
    m.SetAdditionalData(make(map[string]any))
    return m
}
// CreateCheckpointPodFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateCheckpointPodFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewCheckpointPod(), nil
}
// GetActionId gets the action_id property value. The action_id property
// returns a *string when successful
func (m *CheckpointPod) GetActionId()(*string) {
    return m.action_id
}
// GetAdditionalData gets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
// returns a map[string]any when successful
func (m *CheckpointPod) GetAdditionalData()(map[string]any) {
    return m.additionalData
}
// GetClusterId gets the cluster_id property value. The cluster_id property
// returns a *string when successful
func (m *CheckpointPod) GetClusterId()(*string) {
    return m.cluster_id
}
// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error) when successful
func (m *CheckpointPod) GetFieldDeserializers()(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error)) {
    res := make(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error))
    res["action_id"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetActionId(val)
        }
        return nil
    }
    res["cluster_id"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetClusterId(val)
        }
        return nil
    }
    res["kind"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetEnumValue(ParseCheckpointKind)
        if err != nil {
            return err
        }
        if val != nil {
            m.SetKind(val.(*CheckpointKind))
        }
        return nil
    }
    res["namespace"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetNamespace(val)
        }
        return nil
    }
    res["pod_id"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetPodId(val)
        }
        return nil
    }
    res["pod_name"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetPodName(val)
        }
        return nil
    }
    res["runc_root"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetRuncRoot(val)
        }
        return nil
    }
    return res
}
// GetKind gets the kind property value. The kind property
// returns a *CheckpointKind when successful
func (m *CheckpointPod) GetKind()(*CheckpointKind) {
    return m.kind
}
// GetNamespace gets the namespace property value. The namespace property
// returns a *string when successful
func (m *CheckpointPod) GetNamespace()(*string) {
    return m.namespace
}
// GetPodId gets the pod_id property value. The pod_id property
// returns a *string when successful
func (m *CheckpointPod) GetPodId()(*string) {
    return m.pod_id
}
// GetPodName gets the pod_name property value. The pod_name property
// returns a *string when successful
func (m *CheckpointPod) GetPodName()(*string) {
    return m.pod_name
}
// GetRuncRoot gets the runc_root property value. The runc_root property
// returns a *string when successful
func (m *CheckpointPod) GetRuncRoot()(*string) {
    return m.runc_root
}
// Serialize serializes information the current object
func (m *CheckpointPod) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter)(error) {
    {
        err := writer.WriteStringValue("cluster_id", m.GetClusterId())
        if err != nil {
            return err
        }
    }
    if m.GetKind() != nil {
        cast := (*m.GetKind()).String()
        err := writer.WriteStringValue("kind", &cast)
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("namespace", m.GetNamespace())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("pod_id", m.GetPodId())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("pod_name", m.GetPodName())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("runc_root", m.GetRuncRoot())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteAdditionalData(m.GetAdditionalData())
        if err != nil {
            return err
        }
    }
    return nil
}
// SetActionId sets the action_id property value. The action_id property
func (m *CheckpointPod) SetActionId(value *string)() {
    m.action_id = value
}
// SetAdditionalData sets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
func (m *CheckpointPod) SetAdditionalData(value map[string]any)() {
    m.additionalData = value
}
// SetClusterId sets the cluster_id property value. The cluster_id property
func (m *CheckpointPod) SetClusterId(value *string)() {
    m.cluster_id = value
}
// SetKind sets the kind property value. The kind property
func (m *CheckpointPod) SetKind(value *CheckpointKind)() {
    m.kind = value
}
// SetNamespace sets the namespace property value. The namespace property
func (m *CheckpointPod) SetNamespace(value *string)() {
    m.namespace = value
}
// SetPodId sets the pod_id property value. The pod_id property
func (m *CheckpointPod) SetPodId(value *string)() {
    m.pod_id = value
}
// SetPodName sets the pod_name property value. The pod_name property
func (m *CheckpointPod) SetPodName(value *string)() {
    m.pod_name = value
}
// SetRuncRoot sets the runc_root property value. The runc_root property
func (m *CheckpointPod) SetRuncRoot(value *string)() {
    m.runc_root = value
}
type CheckpointPodable interface {
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.AdditionalDataHolder
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
    GetActionId()(*string)
    GetClusterId()(*string)
    GetKind()(*CheckpointKind)
    GetNamespace()(*string)
    GetPodId()(*string)
    GetPodName()(*string)
    GetRuncRoot()(*string)
    SetActionId(value *string)()
    SetClusterId(value *string)()
    SetKind(value *CheckpointKind)()
    SetNamespace(value *string)()
    SetPodId(value *string)()
    SetPodName(value *string)()
    SetRuncRoot(value *string)()
}
