// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package models

import (
	i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// CostSavingsEstimate cost savings estimate with user-provided hourly rate
type CostSavingsEstimate struct {
	// Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
	additionalData map[string]any
	// Cost of checkpoint overhead (time spent checkpointing)
	checkpoint_overhead_cost *float64
	// User-provided hourly compute cost
	hourly_rate *float64
	// Maximum potential data loss on failure (seconds) - worst case recovery point
	max_recovery_point_seconds *float64
	// Estimated maximum cost saved per failure event(time_protected - max_recovery_point) * hourly_rate / 3600
	max_savings_per_failure *float64
	// Net potential savings = max_savings - overhead_cost
	net_potential_savings *float64
	// Number of pods protected
	pods_protected *int64
	// Total time protected by checkpoints (seconds)
	time_protected_seconds *float64
	// Total checkpoints taken
	total_checkpoints *int64
}

// NewCostSavingsEstimate instantiates a new CostSavingsEstimate and sets the default values.
func NewCostSavingsEstimate() *CostSavingsEstimate {
	m := &CostSavingsEstimate{}
	m.SetAdditionalData(make(map[string]any))
	return m
}

// CreateCostSavingsEstimateFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateCostSavingsEstimateFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) (i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
	return NewCostSavingsEstimate(), nil
}

// GetAdditionalData gets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
// returns a map[string]any when successful
func (m *CostSavingsEstimate) GetAdditionalData() map[string]any {
	return m.additionalData
}

// GetCheckpointOverheadCost gets the checkpoint_overhead_cost property value. Cost of checkpoint overhead (time spent checkpointing)
// returns a *float64 when successful
func (m *CostSavingsEstimate) GetCheckpointOverheadCost() *float64 {
	return m.checkpoint_overhead_cost
}

// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error when successful
func (m *CostSavingsEstimate) GetFieldDeserializers() map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
	res := make(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error)
	res["checkpoint_overhead_cost"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetFloat64Value()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetCheckpointOverheadCost(val)
		}
		return nil
	}
	res["hourly_rate"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetFloat64Value()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetHourlyRate(val)
		}
		return nil
	}
	res["max_recovery_point_seconds"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetFloat64Value()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetMaxRecoveryPointSeconds(val)
		}
		return nil
	}
	res["max_savings_per_failure"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetFloat64Value()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetMaxSavingsPerFailure(val)
		}
		return nil
	}
	res["net_potential_savings"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetFloat64Value()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetNetPotentialSavings(val)
		}
		return nil
	}
	res["pods_protected"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetInt64Value()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetPodsProtected(val)
		}
		return nil
	}
	res["time_protected_seconds"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetFloat64Value()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetTimeProtectedSeconds(val)
		}
		return nil
	}
	res["total_checkpoints"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetInt64Value()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetTotalCheckpoints(val)
		}
		return nil
	}
	return res
}

// GetHourlyRate gets the hourly_rate property value. User-provided hourly compute cost
// returns a *float64 when successful
func (m *CostSavingsEstimate) GetHourlyRate() *float64 {
	return m.hourly_rate
}

// GetMaxRecoveryPointSeconds gets the max_recovery_point_seconds property value. Maximum potential data loss on failure (seconds) - worst case recovery point
// returns a *float64 when successful
func (m *CostSavingsEstimate) GetMaxRecoveryPointSeconds() *float64 {
	return m.max_recovery_point_seconds
}

// GetMaxSavingsPerFailure gets the max_savings_per_failure property value. Estimated maximum cost saved per failure event(time_protected - max_recovery_point) * hourly_rate / 3600
// returns a *float64 when successful
func (m *CostSavingsEstimate) GetMaxSavingsPerFailure() *float64 {
	return m.max_savings_per_failure
}

// GetNetPotentialSavings gets the net_potential_savings property value. Net potential savings = max_savings - overhead_cost
// returns a *float64 when successful
func (m *CostSavingsEstimate) GetNetPotentialSavings() *float64 {
	return m.net_potential_savings
}

// GetPodsProtected gets the pods_protected property value. Number of pods protected
// returns a *int64 when successful
func (m *CostSavingsEstimate) GetPodsProtected() *int64 {
	return m.pods_protected
}

// GetTimeProtectedSeconds gets the time_protected_seconds property value. Total time protected by checkpoints (seconds)
// returns a *float64 when successful
func (m *CostSavingsEstimate) GetTimeProtectedSeconds() *float64 {
	return m.time_protected_seconds
}

// GetTotalCheckpoints gets the total_checkpoints property value. Total checkpoints taken
// returns a *int64 when successful
func (m *CostSavingsEstimate) GetTotalCheckpoints() *int64 {
	return m.total_checkpoints
}

// Serialize serializes information the current object
func (m *CostSavingsEstimate) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter) error {
	{
		err := writer.WriteFloat64Value("checkpoint_overhead_cost", m.GetCheckpointOverheadCost())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteFloat64Value("hourly_rate", m.GetHourlyRate())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteFloat64Value("max_recovery_point_seconds", m.GetMaxRecoveryPointSeconds())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteFloat64Value("max_savings_per_failure", m.GetMaxSavingsPerFailure())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteFloat64Value("net_potential_savings", m.GetNetPotentialSavings())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteInt64Value("pods_protected", m.GetPodsProtected())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteFloat64Value("time_protected_seconds", m.GetTimeProtectedSeconds())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteInt64Value("total_checkpoints", m.GetTotalCheckpoints())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteAdditionalData(m.GetAdditionalData())
		if err != nil {
			return err
		}
	}
	return nil
}

// SetAdditionalData sets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
func (m *CostSavingsEstimate) SetAdditionalData(value map[string]any) {
	m.additionalData = value
}

// SetCheckpointOverheadCost sets the checkpoint_overhead_cost property value. Cost of checkpoint overhead (time spent checkpointing)
func (m *CostSavingsEstimate) SetCheckpointOverheadCost(value *float64) {
	m.checkpoint_overhead_cost = value
}

// SetHourlyRate sets the hourly_rate property value. User-provided hourly compute cost
func (m *CostSavingsEstimate) SetHourlyRate(value *float64) {
	m.hourly_rate = value
}

// SetMaxRecoveryPointSeconds sets the max_recovery_point_seconds property value. Maximum potential data loss on failure (seconds) - worst case recovery point
func (m *CostSavingsEstimate) SetMaxRecoveryPointSeconds(value *float64) {
	m.max_recovery_point_seconds = value
}

// SetMaxSavingsPerFailure sets the max_savings_per_failure property value. Estimated maximum cost saved per failure event(time_protected - max_recovery_point) * hourly_rate / 3600
func (m *CostSavingsEstimate) SetMaxSavingsPerFailure(value *float64) {
	m.max_savings_per_failure = value
}

// SetNetPotentialSavings sets the net_potential_savings property value. Net potential savings = max_savings - overhead_cost
func (m *CostSavingsEstimate) SetNetPotentialSavings(value *float64) {
	m.net_potential_savings = value
}

// SetPodsProtected sets the pods_protected property value. Number of pods protected
func (m *CostSavingsEstimate) SetPodsProtected(value *int64) {
	m.pods_protected = value
}

// SetTimeProtectedSeconds sets the time_protected_seconds property value. Total time protected by checkpoints (seconds)
func (m *CostSavingsEstimate) SetTimeProtectedSeconds(value *float64) {
	m.time_protected_seconds = value
}

// SetTotalCheckpoints sets the total_checkpoints property value. Total checkpoints taken
func (m *CostSavingsEstimate) SetTotalCheckpoints(value *int64) {
	m.total_checkpoints = value
}

type CostSavingsEstimateable interface {
	i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.AdditionalDataHolder
	i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
	GetCheckpointOverheadCost() *float64
	GetHourlyRate() *float64
	GetMaxRecoveryPointSeconds() *float64
	GetMaxSavingsPerFailure() *float64
	GetNetPotentialSavings() *float64
	GetPodsProtected() *int64
	GetTimeProtectedSeconds() *float64
	GetTotalCheckpoints() *int64
	SetCheckpointOverheadCost(value *float64)
	SetHourlyRate(value *float64)
	SetMaxRecoveryPointSeconds(value *float64)
	SetMaxSavingsPerFailure(value *float64)
	SetNetPotentialSavings(value *float64)
	SetPodsProtected(value *int64)
	SetTimeProtectedSeconds(value *float64)
	SetTotalCheckpoints(value *int64)
}
