// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package models

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

type CreateInstanceResponse struct {
    // Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
    additionalData map[string]any
    // The cloud_provider property
    cloud_provider *string
    // The instance_id property
    instance_id *string
    // The instance_type property
    instance_type *string
    // The region property
    region *string
    // The status property
    status *string
}
// NewCreateInstanceResponse instantiates a new CreateInstanceResponse and sets the default values.
func NewCreateInstanceResponse()(*CreateInstanceResponse) {
    m := &CreateInstanceResponse{
    }
    m.SetAdditionalData(make(map[string]any))
    return m
}
// CreateCreateInstanceResponseFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateCreateInstanceResponseFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewCreateInstanceResponse(), nil
}
// GetAdditionalData gets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
// returns a map[string]any when successful
func (m *CreateInstanceResponse) GetAdditionalData()(map[string]any) {
    return m.additionalData
}
// GetCloudProvider gets the cloud_provider property value. The cloud_provider property
// returns a *string when successful
func (m *CreateInstanceResponse) GetCloudProvider()(*string) {
    return m.cloud_provider
}
// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error) when successful
func (m *CreateInstanceResponse) GetFieldDeserializers()(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error)) {
    res := make(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error))
    res["cloud_provider"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetCloudProvider(val)
        }
        return nil
    }
    res["instance_id"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetInstanceId(val)
        }
        return nil
    }
    res["instance_type"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetInstanceType(val)
        }
        return nil
    }
    res["region"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetRegion(val)
        }
        return nil
    }
    res["status"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetStatus(val)
        }
        return nil
    }
    return res
}
// GetInstanceId gets the instance_id property value. The instance_id property
// returns a *string when successful
func (m *CreateInstanceResponse) GetInstanceId()(*string) {
    return m.instance_id
}
// GetInstanceType gets the instance_type property value. The instance_type property
// returns a *string when successful
func (m *CreateInstanceResponse) GetInstanceType()(*string) {
    return m.instance_type
}
// GetRegion gets the region property value. The region property
// returns a *string when successful
func (m *CreateInstanceResponse) GetRegion()(*string) {
    return m.region
}
// GetStatus gets the status property value. The status property
// returns a *string when successful
func (m *CreateInstanceResponse) GetStatus()(*string) {
    return m.status
}
// Serialize serializes information the current object
func (m *CreateInstanceResponse) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter)(error) {
    {
        err := writer.WriteStringValue("cloud_provider", m.GetCloudProvider())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("instance_id", m.GetInstanceId())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("instance_type", m.GetInstanceType())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("region", m.GetRegion())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("status", m.GetStatus())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteAdditionalData(m.GetAdditionalData())
        if err != nil {
            return err
        }
    }
    return nil
}
// SetAdditionalData sets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
func (m *CreateInstanceResponse) SetAdditionalData(value map[string]any)() {
    m.additionalData = value
}
// SetCloudProvider sets the cloud_provider property value. The cloud_provider property
func (m *CreateInstanceResponse) SetCloudProvider(value *string)() {
    m.cloud_provider = value
}
// SetInstanceId sets the instance_id property value. The instance_id property
func (m *CreateInstanceResponse) SetInstanceId(value *string)() {
    m.instance_id = value
}
// SetInstanceType sets the instance_type property value. The instance_type property
func (m *CreateInstanceResponse) SetInstanceType(value *string)() {
    m.instance_type = value
}
// SetRegion sets the region property value. The region property
func (m *CreateInstanceResponse) SetRegion(value *string)() {
    m.region = value
}
// SetStatus sets the status property value. The status property
func (m *CreateInstanceResponse) SetStatus(value *string)() {
    m.status = value
}
type CreateInstanceResponseable interface {
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.AdditionalDataHolder
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
    GetCloudProvider()(*string)
    GetInstanceId()(*string)
    GetInstanceType()(*string)
    GetRegion()(*string)
    GetStatus()(*string)
    SetCloudProvider(value *string)()
    SetInstanceId(value *string)()
    SetInstanceType(value *string)()
    SetRegion(value *string)()
    SetStatus(value *string)()
}
