// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package models

import (
	i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

type CreateInstanceRequest struct {
	// Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
	additionalData map[string]any
	// The alert property
	alert Alertable
	// The auto_delete property
	auto_delete AutoDeleteable
	// The cloud property
	cloud *string
	// The envs property
	envs []EnvironmentVariableable
	// The launch_configuration property
	launch_configuration LaunchConfigurationable
	// The name property
	name *string
	// The os property
	os *string
	// The region property
	region *string
	// The shade_cloud property
	shade_cloud *bool
	// The shade_instance_type property
	shade_instance_type *string
	// The ssh_key_id property
	ssh_key_id *string
	// The tags property
	tags []string
	// The template_id property
	template_id *string
	// The volume_ids property
	volume_ids []string
	// The volume_mount property
	volume_mount VolumeMountable
}

// NewCreateInstanceRequest instantiates a new CreateInstanceRequest and sets the default values.
func NewCreateInstanceRequest() *CreateInstanceRequest {
	m := &CreateInstanceRequest{}
	m.SetAdditionalData(make(map[string]any))
	return m
}

// CreateCreateInstanceRequestFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateCreateInstanceRequestFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) (i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
	return NewCreateInstanceRequest(), nil
}

// GetAdditionalData gets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
// returns a map[string]any when successful
func (m *CreateInstanceRequest) GetAdditionalData() map[string]any {
	return m.additionalData
}

// GetAlert gets the alert property value. The alert property
// returns a Alertable when successful
func (m *CreateInstanceRequest) GetAlert() Alertable {
	return m.alert
}

// GetAutoDelete gets the auto_delete property value. The auto_delete property
// returns a AutoDeleteable when successful
func (m *CreateInstanceRequest) GetAutoDelete() AutoDeleteable {
	return m.auto_delete
}

// GetCloud gets the cloud property value. The cloud property
// returns a *string when successful
func (m *CreateInstanceRequest) GetCloud() *string {
	return m.cloud
}

// GetEnvs gets the envs property value. The envs property
// returns a []EnvironmentVariableable when successful
func (m *CreateInstanceRequest) GetEnvs() []EnvironmentVariableable {
	return m.envs
}

// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error when successful
func (m *CreateInstanceRequest) GetFieldDeserializers() map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
	res := make(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error)
	res["alert"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetObjectValue(CreateAlertFromDiscriminatorValue)
		if err != nil {
			return err
		}
		if val != nil {
			m.SetAlert(val.(Alertable))
		}
		return nil
	}
	res["auto_delete"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetObjectValue(CreateAutoDeleteFromDiscriminatorValue)
		if err != nil {
			return err
		}
		if val != nil {
			m.SetAutoDelete(val.(AutoDeleteable))
		}
		return nil
	}
	res["cloud"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetStringValue()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetCloud(val)
		}
		return nil
	}
	res["envs"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetCollectionOfObjectValues(CreateEnvironmentVariableFromDiscriminatorValue)
		if err != nil {
			return err
		}
		if val != nil {
			res := make([]EnvironmentVariableable, len(val))
			for i, v := range val {
				if v != nil {
					res[i] = v.(EnvironmentVariableable)
				}
			}
			m.SetEnvs(res)
		}
		return nil
	}
	res["launch_configuration"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetObjectValue(CreateLaunchConfigurationFromDiscriminatorValue)
		if err != nil {
			return err
		}
		if val != nil {
			m.SetLaunchConfiguration(val.(LaunchConfigurationable))
		}
		return nil
	}
	res["name"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetStringValue()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetName(val)
		}
		return nil
	}
	res["os"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetStringValue()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetOs(val)
		}
		return nil
	}
	res["region"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetStringValue()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetRegion(val)
		}
		return nil
	}
	res["shade_cloud"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetBoolValue()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetShadeCloud(val)
		}
		return nil
	}
	res["shade_instance_type"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetStringValue()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetShadeInstanceType(val)
		}
		return nil
	}
	res["ssh_key_id"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetStringValue()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetSshKeyId(val)
		}
		return nil
	}
	res["tags"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetCollectionOfPrimitiveValues("string")
		if err != nil {
			return err
		}
		if val != nil {
			res := make([]string, len(val))
			for i, v := range val {
				if v != nil {
					res[i] = *(v.(*string))
				}
			}
			m.SetTags(res)
		}
		return nil
	}
	res["template_id"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetStringValue()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetTemplateId(val)
		}
		return nil
	}
	res["volume_ids"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetCollectionOfPrimitiveValues("string")
		if err != nil {
			return err
		}
		if val != nil {
			res := make([]string, len(val))
			for i, v := range val {
				if v != nil {
					res[i] = *(v.(*string))
				}
			}
			m.SetVolumeIds(res)
		}
		return nil
	}
	res["volume_mount"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetObjectValue(CreateVolumeMountFromDiscriminatorValue)
		if err != nil {
			return err
		}
		if val != nil {
			m.SetVolumeMount(val.(VolumeMountable))
		}
		return nil
	}
	return res
}

// GetLaunchConfiguration gets the launch_configuration property value. The launch_configuration property
// returns a LaunchConfigurationable when successful
func (m *CreateInstanceRequest) GetLaunchConfiguration() LaunchConfigurationable {
	return m.launch_configuration
}

// GetName gets the name property value. The name property
// returns a *string when successful
func (m *CreateInstanceRequest) GetName() *string {
	return m.name
}

// GetOs gets the os property value. The os property
// returns a *string when successful
func (m *CreateInstanceRequest) GetOs() *string {
	return m.os
}

// GetRegion gets the region property value. The region property
// returns a *string when successful
func (m *CreateInstanceRequest) GetRegion() *string {
	return m.region
}

// GetShadeCloud gets the shade_cloud property value. The shade_cloud property
// returns a *bool when successful
func (m *CreateInstanceRequest) GetShadeCloud() *bool {
	return m.shade_cloud
}

// GetShadeInstanceType gets the shade_instance_type property value. The shade_instance_type property
// returns a *string when successful
func (m *CreateInstanceRequest) GetShadeInstanceType() *string {
	return m.shade_instance_type
}

// GetSshKeyId gets the ssh_key_id property value. The ssh_key_id property
// returns a *string when successful
func (m *CreateInstanceRequest) GetSshKeyId() *string {
	return m.ssh_key_id
}

// GetTags gets the tags property value. The tags property
// returns a []string when successful
func (m *CreateInstanceRequest) GetTags() []string {
	return m.tags
}

// GetTemplateId gets the template_id property value. The template_id property
// returns a *string when successful
func (m *CreateInstanceRequest) GetTemplateId() *string {
	return m.template_id
}

// GetVolumeIds gets the volume_ids property value. The volume_ids property
// returns a []string when successful
func (m *CreateInstanceRequest) GetVolumeIds() []string {
	return m.volume_ids
}

// GetVolumeMount gets the volume_mount property value. The volume_mount property
// returns a VolumeMountable when successful
func (m *CreateInstanceRequest) GetVolumeMount() VolumeMountable {
	return m.volume_mount
}

// Serialize serializes information the current object
func (m *CreateInstanceRequest) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter) error {
	{
		err := writer.WriteObjectValue("alert", m.GetAlert())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteObjectValue("auto_delete", m.GetAutoDelete())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteStringValue("cloud", m.GetCloud())
		if err != nil {
			return err
		}
	}
	if m.GetEnvs() != nil {
		cast := make([]i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, len(m.GetEnvs()))
		for i, v := range m.GetEnvs() {
			if v != nil {
				cast[i] = v.(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable)
			}
		}
		err := writer.WriteCollectionOfObjectValues("envs", cast)
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteObjectValue("launch_configuration", m.GetLaunchConfiguration())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteStringValue("name", m.GetName())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteStringValue("os", m.GetOs())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteStringValue("region", m.GetRegion())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteBoolValue("shade_cloud", m.GetShadeCloud())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteStringValue("shade_instance_type", m.GetShadeInstanceType())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteStringValue("ssh_key_id", m.GetSshKeyId())
		if err != nil {
			return err
		}
	}
	if m.GetTags() != nil {
		err := writer.WriteCollectionOfStringValues("tags", m.GetTags())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteStringValue("template_id", m.GetTemplateId())
		if err != nil {
			return err
		}
	}
	if m.GetVolumeIds() != nil {
		err := writer.WriteCollectionOfStringValues("volume_ids", m.GetVolumeIds())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteObjectValue("volume_mount", m.GetVolumeMount())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteAdditionalData(m.GetAdditionalData())
		if err != nil {
			return err
		}
	}
	return nil
}

// SetAdditionalData sets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
func (m *CreateInstanceRequest) SetAdditionalData(value map[string]any) {
	m.additionalData = value
}

// SetAlert sets the alert property value. The alert property
func (m *CreateInstanceRequest) SetAlert(value Alertable) {
	m.alert = value
}

// SetAutoDelete sets the auto_delete property value. The auto_delete property
func (m *CreateInstanceRequest) SetAutoDelete(value AutoDeleteable) {
	m.auto_delete = value
}

// SetCloud sets the cloud property value. The cloud property
func (m *CreateInstanceRequest) SetCloud(value *string) {
	m.cloud = value
}

// SetEnvs sets the envs property value. The envs property
func (m *CreateInstanceRequest) SetEnvs(value []EnvironmentVariableable) {
	m.envs = value
}

// SetLaunchConfiguration sets the launch_configuration property value. The launch_configuration property
func (m *CreateInstanceRequest) SetLaunchConfiguration(value LaunchConfigurationable) {
	m.launch_configuration = value
}

// SetName sets the name property value. The name property
func (m *CreateInstanceRequest) SetName(value *string) {
	m.name = value
}

// SetOs sets the os property value. The os property
func (m *CreateInstanceRequest) SetOs(value *string) {
	m.os = value
}

// SetRegion sets the region property value. The region property
func (m *CreateInstanceRequest) SetRegion(value *string) {
	m.region = value
}

// SetShadeCloud sets the shade_cloud property value. The shade_cloud property
func (m *CreateInstanceRequest) SetShadeCloud(value *bool) {
	m.shade_cloud = value
}

// SetShadeInstanceType sets the shade_instance_type property value. The shade_instance_type property
func (m *CreateInstanceRequest) SetShadeInstanceType(value *string) {
	m.shade_instance_type = value
}

// SetSshKeyId sets the ssh_key_id property value. The ssh_key_id property
func (m *CreateInstanceRequest) SetSshKeyId(value *string) {
	m.ssh_key_id = value
}

// SetTags sets the tags property value. The tags property
func (m *CreateInstanceRequest) SetTags(value []string) {
	m.tags = value
}

// SetTemplateId sets the template_id property value. The template_id property
func (m *CreateInstanceRequest) SetTemplateId(value *string) {
	m.template_id = value
}

// SetVolumeIds sets the volume_ids property value. The volume_ids property
func (m *CreateInstanceRequest) SetVolumeIds(value []string) {
	m.volume_ids = value
}

// SetVolumeMount sets the volume_mount property value. The volume_mount property
func (m *CreateInstanceRequest) SetVolumeMount(value VolumeMountable) {
	m.volume_mount = value
}

type CreateInstanceRequestable interface {
	i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.AdditionalDataHolder
	i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
	GetAlert() Alertable
	GetAutoDelete() AutoDeleteable
	GetCloud() *string
	GetEnvs() []EnvironmentVariableable
	GetLaunchConfiguration() LaunchConfigurationable
	GetName() *string
	GetOs() *string
	GetRegion() *string
	GetShadeCloud() *bool
	GetShadeInstanceType() *string
	GetSshKeyId() *string
	GetTags() []string
	GetTemplateId() *string
	GetVolumeIds() []string
	GetVolumeMount() VolumeMountable
	SetAlert(value Alertable)
	SetAutoDelete(value AutoDeleteable)
	SetCloud(value *string)
	SetEnvs(value []EnvironmentVariableable)
	SetLaunchConfiguration(value LaunchConfigurationable)
	SetName(value *string)
	SetOs(value *string)
	SetRegion(value *string)
	SetShadeCloud(value *bool)
	SetShadeInstanceType(value *string)
	SetSshKeyId(value *string)
	SetTags(value []string)
	SetTemplateId(value *string)
	SetVolumeIds(value []string)
	SetVolumeMount(value VolumeMountable)
}
