// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package models

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// DynamoCheckpointedWorker one worker pod that a checkpoint was issued for.
type DynamoCheckpointedWorker struct {
    // The action_id property
    action_id *string
    // Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
    additionalData map[string]any
    // The pod_name property
    pod_name *string
}
// NewDynamoCheckpointedWorker instantiates a new DynamoCheckpointedWorker and sets the default values.
func NewDynamoCheckpointedWorker()(*DynamoCheckpointedWorker) {
    m := &DynamoCheckpointedWorker{
    }
    m.SetAdditionalData(make(map[string]any))
    return m
}
// CreateDynamoCheckpointedWorkerFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateDynamoCheckpointedWorkerFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewDynamoCheckpointedWorker(), nil
}
// GetActionId gets the action_id property value. The action_id property
// returns a *string when successful
func (m *DynamoCheckpointedWorker) GetActionId()(*string) {
    return m.action_id
}
// GetAdditionalData gets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
// returns a map[string]any when successful
func (m *DynamoCheckpointedWorker) GetAdditionalData()(map[string]any) {
    return m.additionalData
}
// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error) when successful
func (m *DynamoCheckpointedWorker) GetFieldDeserializers()(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error)) {
    res := make(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error))
    res["action_id"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetActionId(val)
        }
        return nil
    }
    res["pod_name"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetPodName(val)
        }
        return nil
    }
    return res
}
// GetPodName gets the pod_name property value. The pod_name property
// returns a *string when successful
func (m *DynamoCheckpointedWorker) GetPodName()(*string) {
    return m.pod_name
}
// Serialize serializes information the current object
func (m *DynamoCheckpointedWorker) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter)(error) {
    {
        err := writer.WriteStringValue("action_id", m.GetActionId())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("pod_name", m.GetPodName())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteAdditionalData(m.GetAdditionalData())
        if err != nil {
            return err
        }
    }
    return nil
}
// SetActionId sets the action_id property value. The action_id property
func (m *DynamoCheckpointedWorker) SetActionId(value *string)() {
    m.action_id = value
}
// SetAdditionalData sets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
func (m *DynamoCheckpointedWorker) SetAdditionalData(value map[string]any)() {
    m.additionalData = value
}
// SetPodName sets the pod_name property value. The pod_name property
func (m *DynamoCheckpointedWorker) SetPodName(value *string)() {
    m.pod_name = value
}
type DynamoCheckpointedWorkerable interface {
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.AdditionalDataHolder
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
    GetActionId()(*string)
    GetPodName()(*string)
    SetActionId(value *string)()
    SetPodName(value *string)()
}
