// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package models

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// DynamoDeployRequest request body for submitting a DynamoGraphDeployment to a cluster.
type DynamoDeployRequest struct {
    // Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
    additionalData map[string]any
    // ID of the target cluster
    cluster_id *string
    // If true, inject runtimeClassName: cedana and CEDANA_CHECKPOINT into worker pod specs
    enable_checkpointing *bool
    // Full DynamoGraphDeployment manifest (nvidia.com/v1alpha1)
    manifest i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.UntypedNodeable
}
// NewDynamoDeployRequest instantiates a new DynamoDeployRequest and sets the default values.
func NewDynamoDeployRequest()(*DynamoDeployRequest) {
    m := &DynamoDeployRequest{
    }
    m.SetAdditionalData(make(map[string]any))
    return m
}
// CreateDynamoDeployRequestFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateDynamoDeployRequestFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewDynamoDeployRequest(), nil
}
// GetAdditionalData gets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
// returns a map[string]any when successful
func (m *DynamoDeployRequest) GetAdditionalData()(map[string]any) {
    return m.additionalData
}
// GetClusterId gets the cluster_id property value. ID of the target cluster
// returns a *string when successful
func (m *DynamoDeployRequest) GetClusterId()(*string) {
    return m.cluster_id
}
// GetEnableCheckpointing gets the enable_checkpointing property value. If true, inject runtimeClassName: cedana and CEDANA_CHECKPOINT into worker pod specs
// returns a *bool when successful
func (m *DynamoDeployRequest) GetEnableCheckpointing()(*bool) {
    return m.enable_checkpointing
}
// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error) when successful
func (m *DynamoDeployRequest) GetFieldDeserializers()(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error)) {
    res := make(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error))
    res["cluster_id"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetClusterId(val)
        }
        return nil
    }
    res["enable_checkpointing"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetBoolValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetEnableCheckpointing(val)
        }
        return nil
    }
    res["manifest"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetObjectValue(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.CreateUntypedNodeFromDiscriminatorValue)
        if err != nil {
            return err
        }
        if val != nil {
            m.SetManifest(val.(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.UntypedNodeable))
        }
        return nil
    }
    return res
}
// GetManifest gets the manifest property value. Full DynamoGraphDeployment manifest (nvidia.com/v1alpha1)
// returns a UntypedNodeable when successful
func (m *DynamoDeployRequest) GetManifest()(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.UntypedNodeable) {
    return m.manifest
}
// Serialize serializes information the current object
func (m *DynamoDeployRequest) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter)(error) {
    {
        err := writer.WriteStringValue("cluster_id", m.GetClusterId())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteBoolValue("enable_checkpointing", m.GetEnableCheckpointing())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteObjectValue("manifest", m.GetManifest())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteAdditionalData(m.GetAdditionalData())
        if err != nil {
            return err
        }
    }
    return nil
}
// SetAdditionalData sets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
func (m *DynamoDeployRequest) SetAdditionalData(value map[string]any)() {
    m.additionalData = value
}
// SetClusterId sets the cluster_id property value. ID of the target cluster
func (m *DynamoDeployRequest) SetClusterId(value *string)() {
    m.cluster_id = value
}
// SetEnableCheckpointing sets the enable_checkpointing property value. If true, inject runtimeClassName: cedana and CEDANA_CHECKPOINT into worker pod specs
func (m *DynamoDeployRequest) SetEnableCheckpointing(value *bool)() {
    m.enable_checkpointing = value
}
// SetManifest sets the manifest property value. Full DynamoGraphDeployment manifest (nvidia.com/v1alpha1)
func (m *DynamoDeployRequest) SetManifest(value i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.UntypedNodeable)() {
    m.manifest = value
}
type DynamoDeployRequestable interface {
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.AdditionalDataHolder
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
    GetClusterId()(*string)
    GetEnableCheckpointing()(*bool)
    GetManifest()(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.UntypedNodeable)
    SetClusterId(value *string)()
    SetEnableCheckpointing(value *bool)()
    SetManifest(value i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.UntypedNodeable)()
}
