// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package models

import (
	i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

type Host struct {
	// Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
	additionalData map[string]any
	// The CPU property
	cPU HostCpuable
	// The Hostname property
	hostname *string
	// The ID property
	iD *string
	// The KernelArch property
	kernelArch *string
	// The KernelVersion property
	kernelVersion *string
	// The MAC property
	mAC *string
	// The Memory property
	memory HostMemoryable
	// The OS property
	oS *string
	// The Platform property
	platform *string
}

// NewHost instantiates a new Host and sets the default values.
func NewHost() *Host {
	m := &Host{}
	m.SetAdditionalData(make(map[string]any))
	return m
}

// CreateHostFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateHostFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) (i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
	return NewHost(), nil
}

// GetAdditionalData gets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
// returns a map[string]any when successful
func (m *Host) GetAdditionalData() map[string]any {
	return m.additionalData
}

// GetCPU gets the CPU property value. The CPU property
// returns a HostCpuable when successful
func (m *Host) GetCPU() HostCpuable {
	return m.cPU
}

// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error when successful
func (m *Host) GetFieldDeserializers() map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
	res := make(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error)
	res["CPU"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetObjectValue(CreateHostCpuFromDiscriminatorValue)
		if err != nil {
			return err
		}
		if val != nil {
			m.SetCPU(val.(HostCpuable))
		}
		return nil
	}
	res["Hostname"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetStringValue()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetHostname(val)
		}
		return nil
	}
	res["ID"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetStringValue()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetID(val)
		}
		return nil
	}
	res["KernelArch"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetStringValue()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetKernelArch(val)
		}
		return nil
	}
	res["KernelVersion"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetStringValue()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetKernelVersion(val)
		}
		return nil
	}
	res["MAC"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetStringValue()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetMAC(val)
		}
		return nil
	}
	res["Memory"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetObjectValue(CreateHostMemoryFromDiscriminatorValue)
		if err != nil {
			return err
		}
		if val != nil {
			m.SetMemory(val.(HostMemoryable))
		}
		return nil
	}
	res["OS"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetStringValue()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetOS(val)
		}
		return nil
	}
	res["Platform"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetStringValue()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetPlatform(val)
		}
		return nil
	}
	return res
}

// GetHostname gets the Hostname property value. The Hostname property
// returns a *string when successful
func (m *Host) GetHostname() *string {
	return m.hostname
}

// GetID gets the ID property value. The ID property
// returns a *string when successful
func (m *Host) GetID() *string {
	return m.iD
}

// GetKernelArch gets the KernelArch property value. The KernelArch property
// returns a *string when successful
func (m *Host) GetKernelArch() *string {
	return m.kernelArch
}

// GetKernelVersion gets the KernelVersion property value. The KernelVersion property
// returns a *string when successful
func (m *Host) GetKernelVersion() *string {
	return m.kernelVersion
}

// GetMAC gets the MAC property value. The MAC property
// returns a *string when successful
func (m *Host) GetMAC() *string {
	return m.mAC
}

// GetMemory gets the Memory property value. The Memory property
// returns a HostMemoryable when successful
func (m *Host) GetMemory() HostMemoryable {
	return m.memory
}

// GetOS gets the OS property value. The OS property
// returns a *string when successful
func (m *Host) GetOS() *string {
	return m.oS
}

// GetPlatform gets the Platform property value. The Platform property
// returns a *string when successful
func (m *Host) GetPlatform() *string {
	return m.platform
}

// Serialize serializes information the current object
func (m *Host) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter) error {
	{
		err := writer.WriteObjectValue("CPU", m.GetCPU())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteStringValue("Hostname", m.GetHostname())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteStringValue("ID", m.GetID())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteStringValue("KernelArch", m.GetKernelArch())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteStringValue("KernelVersion", m.GetKernelVersion())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteStringValue("MAC", m.GetMAC())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteObjectValue("Memory", m.GetMemory())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteStringValue("OS", m.GetOS())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteStringValue("Platform", m.GetPlatform())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteAdditionalData(m.GetAdditionalData())
		if err != nil {
			return err
		}
	}
	return nil
}

// SetAdditionalData sets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
func (m *Host) SetAdditionalData(value map[string]any) {
	m.additionalData = value
}

// SetCPU sets the CPU property value. The CPU property
func (m *Host) SetCPU(value HostCpuable) {
	m.cPU = value
}

// SetHostname sets the Hostname property value. The Hostname property
func (m *Host) SetHostname(value *string) {
	m.hostname = value
}

// SetID sets the ID property value. The ID property
func (m *Host) SetID(value *string) {
	m.iD = value
}

// SetKernelArch sets the KernelArch property value. The KernelArch property
func (m *Host) SetKernelArch(value *string) {
	m.kernelArch = value
}

// SetKernelVersion sets the KernelVersion property value. The KernelVersion property
func (m *Host) SetKernelVersion(value *string) {
	m.kernelVersion = value
}

// SetMAC sets the MAC property value. The MAC property
func (m *Host) SetMAC(value *string) {
	m.mAC = value
}

// SetMemory sets the Memory property value. The Memory property
func (m *Host) SetMemory(value HostMemoryable) {
	m.memory = value
}

// SetOS sets the OS property value. The OS property
func (m *Host) SetOS(value *string) {
	m.oS = value
}

// SetPlatform sets the Platform property value. The Platform property
func (m *Host) SetPlatform(value *string) {
	m.platform = value
}

type Hostable interface {
	i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.AdditionalDataHolder
	i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
	GetCPU() HostCpuable
	GetHostname() *string
	GetID() *string
	GetKernelArch() *string
	GetKernelVersion() *string
	GetMAC() *string
	GetMemory() HostMemoryable
	GetOS() *string
	GetPlatform() *string
	SetCPU(value HostCpuable)
	SetHostname(value *string)
	SetID(value *string)
	SetKernelArch(value *string)
	SetKernelVersion(value *string)
	SetMAC(value *string)
	SetMemory(value HostMemoryable)
	SetOS(value *string)
	SetPlatform(value *string)
}
