// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package models

import (
    i561e97a8befe7661a44c8f54600992b4207a3a0cf6770e5559949bc276de2e22 "github.com/google/uuid"
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

type InferenceAnalytics struct {
    // Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
    additionalData map[string]any
    // The evidence property
    evidence *string
    // The experiment_id property
    experiment_id *i561e97a8befe7661a44c8f54600992b4207a3a0cf6770e5559949bc276de2e22.UUID
    // The profile_id property
    profile_id *string
    // The sample_count property
    sample_count *int32
    // The serving property
    serving ServingAnalyticsable
    // The startup property
    startup StartupAnalyticsable
    // The storage property
    storage StorageAnalyticsable
    // The window_hours property
    window_hours *int64
}
// NewInferenceAnalytics instantiates a new InferenceAnalytics and sets the default values.
func NewInferenceAnalytics()(*InferenceAnalytics) {
    m := &InferenceAnalytics{
    }
    m.SetAdditionalData(make(map[string]any))
    return m
}
// CreateInferenceAnalyticsFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateInferenceAnalyticsFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewInferenceAnalytics(), nil
}
// GetAdditionalData gets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
// returns a map[string]any when successful
func (m *InferenceAnalytics) GetAdditionalData()(map[string]any) {
    return m.additionalData
}
// GetEvidence gets the evidence property value. The evidence property
// returns a *string when successful
func (m *InferenceAnalytics) GetEvidence()(*string) {
    return m.evidence
}
// GetExperimentId gets the experiment_id property value. The experiment_id property
// returns a *UUID when successful
func (m *InferenceAnalytics) GetExperimentId()(*i561e97a8befe7661a44c8f54600992b4207a3a0cf6770e5559949bc276de2e22.UUID) {
    return m.experiment_id
}
// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error) when successful
func (m *InferenceAnalytics) GetFieldDeserializers()(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error)) {
    res := make(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error))
    res["evidence"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetEvidence(val)
        }
        return nil
    }
    res["experiment_id"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetUUIDValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetExperimentId(val)
        }
        return nil
    }
    res["profile_id"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetProfileId(val)
        }
        return nil
    }
    res["sample_count"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetInt32Value()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetSampleCount(val)
        }
        return nil
    }
    res["serving"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetObjectValue(CreateServingAnalyticsFromDiscriminatorValue)
        if err != nil {
            return err
        }
        if val != nil {
            m.SetServing(val.(ServingAnalyticsable))
        }
        return nil
    }
    res["startup"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetObjectValue(CreateStartupAnalyticsFromDiscriminatorValue)
        if err != nil {
            return err
        }
        if val != nil {
            m.SetStartup(val.(StartupAnalyticsable))
        }
        return nil
    }
    res["storage"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetObjectValue(CreateStorageAnalyticsFromDiscriminatorValue)
        if err != nil {
            return err
        }
        if val != nil {
            m.SetStorage(val.(StorageAnalyticsable))
        }
        return nil
    }
    res["window_hours"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetInt64Value()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetWindowHours(val)
        }
        return nil
    }
    return res
}
// GetProfileId gets the profile_id property value. The profile_id property
// returns a *string when successful
func (m *InferenceAnalytics) GetProfileId()(*string) {
    return m.profile_id
}
// GetSampleCount gets the sample_count property value. The sample_count property
// returns a *int32 when successful
func (m *InferenceAnalytics) GetSampleCount()(*int32) {
    return m.sample_count
}
// GetServing gets the serving property value. The serving property
// returns a ServingAnalyticsable when successful
func (m *InferenceAnalytics) GetServing()(ServingAnalyticsable) {
    return m.serving
}
// GetStartup gets the startup property value. The startup property
// returns a StartupAnalyticsable when successful
func (m *InferenceAnalytics) GetStartup()(StartupAnalyticsable) {
    return m.startup
}
// GetStorage gets the storage property value. The storage property
// returns a StorageAnalyticsable when successful
func (m *InferenceAnalytics) GetStorage()(StorageAnalyticsable) {
    return m.storage
}
// GetWindowHours gets the window_hours property value. The window_hours property
// returns a *int64 when successful
func (m *InferenceAnalytics) GetWindowHours()(*int64) {
    return m.window_hours
}
// Serialize serializes information the current object
func (m *InferenceAnalytics) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter)(error) {
    {
        err := writer.WriteStringValue("evidence", m.GetEvidence())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteUUIDValue("experiment_id", m.GetExperimentId())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("profile_id", m.GetProfileId())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteInt32Value("sample_count", m.GetSampleCount())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteObjectValue("serving", m.GetServing())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteObjectValue("startup", m.GetStartup())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteObjectValue("storage", m.GetStorage())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteInt64Value("window_hours", m.GetWindowHours())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteAdditionalData(m.GetAdditionalData())
        if err != nil {
            return err
        }
    }
    return nil
}
// SetAdditionalData sets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
func (m *InferenceAnalytics) SetAdditionalData(value map[string]any)() {
    m.additionalData = value
}
// SetEvidence sets the evidence property value. The evidence property
func (m *InferenceAnalytics) SetEvidence(value *string)() {
    m.evidence = value
}
// SetExperimentId sets the experiment_id property value. The experiment_id property
func (m *InferenceAnalytics) SetExperimentId(value *i561e97a8befe7661a44c8f54600992b4207a3a0cf6770e5559949bc276de2e22.UUID)() {
    m.experiment_id = value
}
// SetProfileId sets the profile_id property value. The profile_id property
func (m *InferenceAnalytics) SetProfileId(value *string)() {
    m.profile_id = value
}
// SetSampleCount sets the sample_count property value. The sample_count property
func (m *InferenceAnalytics) SetSampleCount(value *int32)() {
    m.sample_count = value
}
// SetServing sets the serving property value. The serving property
func (m *InferenceAnalytics) SetServing(value ServingAnalyticsable)() {
    m.serving = value
}
// SetStartup sets the startup property value. The startup property
func (m *InferenceAnalytics) SetStartup(value StartupAnalyticsable)() {
    m.startup = value
}
// SetStorage sets the storage property value. The storage property
func (m *InferenceAnalytics) SetStorage(value StorageAnalyticsable)() {
    m.storage = value
}
// SetWindowHours sets the window_hours property value. The window_hours property
func (m *InferenceAnalytics) SetWindowHours(value *int64)() {
    m.window_hours = value
}
type InferenceAnalyticsable interface {
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.AdditionalDataHolder
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
    GetEvidence()(*string)
    GetExperimentId()(*i561e97a8befe7661a44c8f54600992b4207a3a0cf6770e5559949bc276de2e22.UUID)
    GetProfileId()(*string)
    GetSampleCount()(*int32)
    GetServing()(ServingAnalyticsable)
    GetStartup()(StartupAnalyticsable)
    GetStorage()(StorageAnalyticsable)
    GetWindowHours()(*int64)
    SetEvidence(value *string)()
    SetExperimentId(value *i561e97a8befe7661a44c8f54600992b4207a3a0cf6770e5559949bc276de2e22.UUID)()
    SetProfileId(value *string)()
    SetSampleCount(value *int32)()
    SetServing(value ServingAnalyticsable)()
    SetStartup(value StartupAnalyticsable)()
    SetStorage(value StorageAnalyticsable)()
    SetWindowHours(value *int64)()
}
