// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package models

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

type InstanceTypeConfiguration struct {
    // Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
    additionalData map[string]any
    // The gpu_type property
    gpu_type *string
    // The interconnect property
    interconnect *string
    // The memory_in_gb property
    memory_in_gb *int32
    // The num_gpus property
    num_gpus *int32
    // The nvlink property
    nvlink *bool
    // The os_options property
    os_options []string
    // The storage_in_gb property
    storage_in_gb *int32
    // The vcpus property
    vcpus *int32
    // The vram_per_gpu_in_gb property
    vram_per_gpu_in_gb *int32
}
// NewInstanceTypeConfiguration instantiates a new InstanceTypeConfiguration and sets the default values.
func NewInstanceTypeConfiguration()(*InstanceTypeConfiguration) {
    m := &InstanceTypeConfiguration{
    }
    m.SetAdditionalData(make(map[string]any))
    return m
}
// CreateInstanceTypeConfigurationFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateInstanceTypeConfigurationFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewInstanceTypeConfiguration(), nil
}
// GetAdditionalData gets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
// returns a map[string]any when successful
func (m *InstanceTypeConfiguration) GetAdditionalData()(map[string]any) {
    return m.additionalData
}
// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error) when successful
func (m *InstanceTypeConfiguration) GetFieldDeserializers()(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error)) {
    res := make(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error))
    res["gpu_type"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetGpuType(val)
        }
        return nil
    }
    res["interconnect"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetInterconnect(val)
        }
        return nil
    }
    res["memory_in_gb"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetInt32Value()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetMemoryInGb(val)
        }
        return nil
    }
    res["num_gpus"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetInt32Value()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetNumGpus(val)
        }
        return nil
    }
    res["nvlink"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetBoolValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetNvlink(val)
        }
        return nil
    }
    res["os_options"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetCollectionOfPrimitiveValues("string")
        if err != nil {
            return err
        }
        if val != nil {
            res := make([]string, len(val))
            for i, v := range val {
                if v != nil {
                    res[i] = *(v.(*string))
                }
            }
            m.SetOsOptions(res)
        }
        return nil
    }
    res["storage_in_gb"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetInt32Value()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetStorageInGb(val)
        }
        return nil
    }
    res["vcpus"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetInt32Value()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetVcpus(val)
        }
        return nil
    }
    res["vram_per_gpu_in_gb"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetInt32Value()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetVramPerGpuInGb(val)
        }
        return nil
    }
    return res
}
// GetGpuType gets the gpu_type property value. The gpu_type property
// returns a *string when successful
func (m *InstanceTypeConfiguration) GetGpuType()(*string) {
    return m.gpu_type
}
// GetInterconnect gets the interconnect property value. The interconnect property
// returns a *string when successful
func (m *InstanceTypeConfiguration) GetInterconnect()(*string) {
    return m.interconnect
}
// GetMemoryInGb gets the memory_in_gb property value. The memory_in_gb property
// returns a *int32 when successful
func (m *InstanceTypeConfiguration) GetMemoryInGb()(*int32) {
    return m.memory_in_gb
}
// GetNumGpus gets the num_gpus property value. The num_gpus property
// returns a *int32 when successful
func (m *InstanceTypeConfiguration) GetNumGpus()(*int32) {
    return m.num_gpus
}
// GetNvlink gets the nvlink property value. The nvlink property
// returns a *bool when successful
func (m *InstanceTypeConfiguration) GetNvlink()(*bool) {
    return m.nvlink
}
// GetOsOptions gets the os_options property value. The os_options property
// returns a []string when successful
func (m *InstanceTypeConfiguration) GetOsOptions()([]string) {
    return m.os_options
}
// GetStorageInGb gets the storage_in_gb property value. The storage_in_gb property
// returns a *int32 when successful
func (m *InstanceTypeConfiguration) GetStorageInGb()(*int32) {
    return m.storage_in_gb
}
// GetVcpus gets the vcpus property value. The vcpus property
// returns a *int32 when successful
func (m *InstanceTypeConfiguration) GetVcpus()(*int32) {
    return m.vcpus
}
// GetVramPerGpuInGb gets the vram_per_gpu_in_gb property value. The vram_per_gpu_in_gb property
// returns a *int32 when successful
func (m *InstanceTypeConfiguration) GetVramPerGpuInGb()(*int32) {
    return m.vram_per_gpu_in_gb
}
// Serialize serializes information the current object
func (m *InstanceTypeConfiguration) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter)(error) {
    {
        err := writer.WriteStringValue("gpu_type", m.GetGpuType())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("interconnect", m.GetInterconnect())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteInt32Value("memory_in_gb", m.GetMemoryInGb())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteInt32Value("num_gpus", m.GetNumGpus())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteBoolValue("nvlink", m.GetNvlink())
        if err != nil {
            return err
        }
    }
    if m.GetOsOptions() != nil {
        err := writer.WriteCollectionOfStringValues("os_options", m.GetOsOptions())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteInt32Value("storage_in_gb", m.GetStorageInGb())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteInt32Value("vcpus", m.GetVcpus())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteInt32Value("vram_per_gpu_in_gb", m.GetVramPerGpuInGb())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteAdditionalData(m.GetAdditionalData())
        if err != nil {
            return err
        }
    }
    return nil
}
// SetAdditionalData sets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
func (m *InstanceTypeConfiguration) SetAdditionalData(value map[string]any)() {
    m.additionalData = value
}
// SetGpuType sets the gpu_type property value. The gpu_type property
func (m *InstanceTypeConfiguration) SetGpuType(value *string)() {
    m.gpu_type = value
}
// SetInterconnect sets the interconnect property value. The interconnect property
func (m *InstanceTypeConfiguration) SetInterconnect(value *string)() {
    m.interconnect = value
}
// SetMemoryInGb sets the memory_in_gb property value. The memory_in_gb property
func (m *InstanceTypeConfiguration) SetMemoryInGb(value *int32)() {
    m.memory_in_gb = value
}
// SetNumGpus sets the num_gpus property value. The num_gpus property
func (m *InstanceTypeConfiguration) SetNumGpus(value *int32)() {
    m.num_gpus = value
}
// SetNvlink sets the nvlink property value. The nvlink property
func (m *InstanceTypeConfiguration) SetNvlink(value *bool)() {
    m.nvlink = value
}
// SetOsOptions sets the os_options property value. The os_options property
func (m *InstanceTypeConfiguration) SetOsOptions(value []string)() {
    m.os_options = value
}
// SetStorageInGb sets the storage_in_gb property value. The storage_in_gb property
func (m *InstanceTypeConfiguration) SetStorageInGb(value *int32)() {
    m.storage_in_gb = value
}
// SetVcpus sets the vcpus property value. The vcpus property
func (m *InstanceTypeConfiguration) SetVcpus(value *int32)() {
    m.vcpus = value
}
// SetVramPerGpuInGb sets the vram_per_gpu_in_gb property value. The vram_per_gpu_in_gb property
func (m *InstanceTypeConfiguration) SetVramPerGpuInGb(value *int32)() {
    m.vram_per_gpu_in_gb = value
}
type InstanceTypeConfigurationable interface {
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.AdditionalDataHolder
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
    GetGpuType()(*string)
    GetInterconnect()(*string)
    GetMemoryInGb()(*int32)
    GetNumGpus()(*int32)
    GetNvlink()(*bool)
    GetOsOptions()([]string)
    GetStorageInGb()(*int32)
    GetVcpus()(*int32)
    GetVramPerGpuInGb()(*int32)
    SetGpuType(value *string)()
    SetInterconnect(value *string)()
    SetMemoryInGb(value *int32)()
    SetNumGpus(value *int32)()
    SetNvlink(value *bool)()
    SetOsOptions(value []string)()
    SetStorageInGb(value *int32)()
    SetVcpus(value *int32)()
    SetVramPerGpuInGb(value *int32)()
}
