// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package models

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

type MetricsSummary struct {
    // Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
    additionalData map[string]any
    // The average_backend_latency_ms property
    average_backend_latency_ms *float64
    // The average_routing_latency_ms property
    average_routing_latency_ms *float64
    // The estimated_cold_start_avoided_ms property
    estimated_cold_start_avoided_ms *int64
    // The fallbacks property
    fallbacks *int64
    // The requests property
    requests *int64
    // The successful_requests property
    successful_requests *int64
}
// NewMetricsSummary instantiates a new MetricsSummary and sets the default values.
func NewMetricsSummary()(*MetricsSummary) {
    m := &MetricsSummary{
    }
    m.SetAdditionalData(make(map[string]any))
    return m
}
// CreateMetricsSummaryFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateMetricsSummaryFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewMetricsSummary(), nil
}
// GetAdditionalData gets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
// returns a map[string]any when successful
func (m *MetricsSummary) GetAdditionalData()(map[string]any) {
    return m.additionalData
}
// GetAverageBackendLatencyMs gets the average_backend_latency_ms property value. The average_backend_latency_ms property
// returns a *float64 when successful
func (m *MetricsSummary) GetAverageBackendLatencyMs()(*float64) {
    return m.average_backend_latency_ms
}
// GetAverageRoutingLatencyMs gets the average_routing_latency_ms property value. The average_routing_latency_ms property
// returns a *float64 when successful
func (m *MetricsSummary) GetAverageRoutingLatencyMs()(*float64) {
    return m.average_routing_latency_ms
}
// GetEstimatedColdStartAvoidedMs gets the estimated_cold_start_avoided_ms property value. The estimated_cold_start_avoided_ms property
// returns a *int64 when successful
func (m *MetricsSummary) GetEstimatedColdStartAvoidedMs()(*int64) {
    return m.estimated_cold_start_avoided_ms
}
// GetFallbacks gets the fallbacks property value. The fallbacks property
// returns a *int64 when successful
func (m *MetricsSummary) GetFallbacks()(*int64) {
    return m.fallbacks
}
// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error) when successful
func (m *MetricsSummary) GetFieldDeserializers()(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error)) {
    res := make(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error))
    res["average_backend_latency_ms"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetFloat64Value()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetAverageBackendLatencyMs(val)
        }
        return nil
    }
    res["average_routing_latency_ms"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetFloat64Value()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetAverageRoutingLatencyMs(val)
        }
        return nil
    }
    res["estimated_cold_start_avoided_ms"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetInt64Value()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetEstimatedColdStartAvoidedMs(val)
        }
        return nil
    }
    res["fallbacks"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetInt64Value()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetFallbacks(val)
        }
        return nil
    }
    res["requests"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetInt64Value()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetRequests(val)
        }
        return nil
    }
    res["successful_requests"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetInt64Value()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetSuccessfulRequests(val)
        }
        return nil
    }
    return res
}
// GetRequests gets the requests property value. The requests property
// returns a *int64 when successful
func (m *MetricsSummary) GetRequests()(*int64) {
    return m.requests
}
// GetSuccessfulRequests gets the successful_requests property value. The successful_requests property
// returns a *int64 when successful
func (m *MetricsSummary) GetSuccessfulRequests()(*int64) {
    return m.successful_requests
}
// Serialize serializes information the current object
func (m *MetricsSummary) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter)(error) {
    {
        err := writer.WriteFloat64Value("average_backend_latency_ms", m.GetAverageBackendLatencyMs())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteFloat64Value("average_routing_latency_ms", m.GetAverageRoutingLatencyMs())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteInt64Value("estimated_cold_start_avoided_ms", m.GetEstimatedColdStartAvoidedMs())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteInt64Value("fallbacks", m.GetFallbacks())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteInt64Value("requests", m.GetRequests())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteInt64Value("successful_requests", m.GetSuccessfulRequests())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteAdditionalData(m.GetAdditionalData())
        if err != nil {
            return err
        }
    }
    return nil
}
// SetAdditionalData sets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
func (m *MetricsSummary) SetAdditionalData(value map[string]any)() {
    m.additionalData = value
}
// SetAverageBackendLatencyMs sets the average_backend_latency_ms property value. The average_backend_latency_ms property
func (m *MetricsSummary) SetAverageBackendLatencyMs(value *float64)() {
    m.average_backend_latency_ms = value
}
// SetAverageRoutingLatencyMs sets the average_routing_latency_ms property value. The average_routing_latency_ms property
func (m *MetricsSummary) SetAverageRoutingLatencyMs(value *float64)() {
    m.average_routing_latency_ms = value
}
// SetEstimatedColdStartAvoidedMs sets the estimated_cold_start_avoided_ms property value. The estimated_cold_start_avoided_ms property
func (m *MetricsSummary) SetEstimatedColdStartAvoidedMs(value *int64)() {
    m.estimated_cold_start_avoided_ms = value
}
// SetFallbacks sets the fallbacks property value. The fallbacks property
func (m *MetricsSummary) SetFallbacks(value *int64)() {
    m.fallbacks = value
}
// SetRequests sets the requests property value. The requests property
func (m *MetricsSummary) SetRequests(value *int64)() {
    m.requests = value
}
// SetSuccessfulRequests sets the successful_requests property value. The successful_requests property
func (m *MetricsSummary) SetSuccessfulRequests(value *int64)() {
    m.successful_requests = value
}
type MetricsSummaryable interface {
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.AdditionalDataHolder
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
    GetAverageBackendLatencyMs()(*float64)
    GetAverageRoutingLatencyMs()(*float64)
    GetEstimatedColdStartAvoidedMs()(*int64)
    GetFallbacks()(*int64)
    GetRequests()(*int64)
    GetSuccessfulRequests()(*int64)
    SetAverageBackendLatencyMs(value *float64)()
    SetAverageRoutingLatencyMs(value *float64)()
    SetEstimatedColdStartAvoidedMs(value *int64)()
    SetFallbacks(value *int64)()
    SetRequests(value *int64)()
    SetSuccessfulRequests(value *int64)()
}
