// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package models

import (
    i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e "time"
    i561e97a8befe7661a44c8f54600992b4207a3a0cf6770e5559949bc276de2e22 "github.com/google/uuid"
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

type Observation struct {
    // Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
    additionalData map[string]any
    // The duration_ms property
    duration_ms *int64
    // The event_type property
    event_type *string
    // The evidence property
    evidence *string
    // The experiment_id property
    experiment_id *i561e97a8befe7661a44c8f54600992b4207a3a0cf6770e5559949bc276de2e22.UUID
    // The id property
    id *i561e97a8befe7661a44c8f54600992b4207a3a0cf6770e5559949bc276de2e22.UUID
    // The observation_key property
    observation_key *string
    // The profile_id property
    profile_id *string
    // The source property
    source *string
    // The started_at property
    started_at *i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time
}
// NewObservation instantiates a new Observation and sets the default values.
func NewObservation()(*Observation) {
    m := &Observation{
    }
    m.SetAdditionalData(make(map[string]any))
    return m
}
// CreateObservationFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateObservationFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewObservation(), nil
}
// GetAdditionalData gets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
// returns a map[string]any when successful
func (m *Observation) GetAdditionalData()(map[string]any) {
    return m.additionalData
}
// GetDurationMs gets the duration_ms property value. The duration_ms property
// returns a *int64 when successful
func (m *Observation) GetDurationMs()(*int64) {
    return m.duration_ms
}
// GetEventType gets the event_type property value. The event_type property
// returns a *string when successful
func (m *Observation) GetEventType()(*string) {
    return m.event_type
}
// GetEvidence gets the evidence property value. The evidence property
// returns a *string when successful
func (m *Observation) GetEvidence()(*string) {
    return m.evidence
}
// GetExperimentId gets the experiment_id property value. The experiment_id property
// returns a *UUID when successful
func (m *Observation) GetExperimentId()(*i561e97a8befe7661a44c8f54600992b4207a3a0cf6770e5559949bc276de2e22.UUID) {
    return m.experiment_id
}
// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error) when successful
func (m *Observation) GetFieldDeserializers()(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error)) {
    res := make(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error))
    res["duration_ms"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetInt64Value()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetDurationMs(val)
        }
        return nil
    }
    res["event_type"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetEventType(val)
        }
        return nil
    }
    res["evidence"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetEvidence(val)
        }
        return nil
    }
    res["experiment_id"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetUUIDValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetExperimentId(val)
        }
        return nil
    }
    res["id"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetUUIDValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetId(val)
        }
        return nil
    }
    res["observation_key"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetObservationKey(val)
        }
        return nil
    }
    res["profile_id"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetProfileId(val)
        }
        return nil
    }
    res["source"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetSource(val)
        }
        return nil
    }
    res["started_at"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetTimeValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetStartedAt(val)
        }
        return nil
    }
    return res
}
// GetId gets the id property value. The id property
// returns a *UUID when successful
func (m *Observation) GetId()(*i561e97a8befe7661a44c8f54600992b4207a3a0cf6770e5559949bc276de2e22.UUID) {
    return m.id
}
// GetObservationKey gets the observation_key property value. The observation_key property
// returns a *string when successful
func (m *Observation) GetObservationKey()(*string) {
    return m.observation_key
}
// GetProfileId gets the profile_id property value. The profile_id property
// returns a *string when successful
func (m *Observation) GetProfileId()(*string) {
    return m.profile_id
}
// GetSource gets the source property value. The source property
// returns a *string when successful
func (m *Observation) GetSource()(*string) {
    return m.source
}
// GetStartedAt gets the started_at property value. The started_at property
// returns a *Time when successful
func (m *Observation) GetStartedAt()(*i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time) {
    return m.started_at
}
// Serialize serializes information the current object
func (m *Observation) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter)(error) {
    {
        err := writer.WriteInt64Value("duration_ms", m.GetDurationMs())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("event_type", m.GetEventType())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("evidence", m.GetEvidence())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteUUIDValue("experiment_id", m.GetExperimentId())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteUUIDValue("id", m.GetId())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("observation_key", m.GetObservationKey())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("profile_id", m.GetProfileId())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("source", m.GetSource())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteTimeValue("started_at", m.GetStartedAt())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteAdditionalData(m.GetAdditionalData())
        if err != nil {
            return err
        }
    }
    return nil
}
// SetAdditionalData sets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
func (m *Observation) SetAdditionalData(value map[string]any)() {
    m.additionalData = value
}
// SetDurationMs sets the duration_ms property value. The duration_ms property
func (m *Observation) SetDurationMs(value *int64)() {
    m.duration_ms = value
}
// SetEventType sets the event_type property value. The event_type property
func (m *Observation) SetEventType(value *string)() {
    m.event_type = value
}
// SetEvidence sets the evidence property value. The evidence property
func (m *Observation) SetEvidence(value *string)() {
    m.evidence = value
}
// SetExperimentId sets the experiment_id property value. The experiment_id property
func (m *Observation) SetExperimentId(value *i561e97a8befe7661a44c8f54600992b4207a3a0cf6770e5559949bc276de2e22.UUID)() {
    m.experiment_id = value
}
// SetId sets the id property value. The id property
func (m *Observation) SetId(value *i561e97a8befe7661a44c8f54600992b4207a3a0cf6770e5559949bc276de2e22.UUID)() {
    m.id = value
}
// SetObservationKey sets the observation_key property value. The observation_key property
func (m *Observation) SetObservationKey(value *string)() {
    m.observation_key = value
}
// SetProfileId sets the profile_id property value. The profile_id property
func (m *Observation) SetProfileId(value *string)() {
    m.profile_id = value
}
// SetSource sets the source property value. The source property
func (m *Observation) SetSource(value *string)() {
    m.source = value
}
// SetStartedAt sets the started_at property value. The started_at property
func (m *Observation) SetStartedAt(value *i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time)() {
    m.started_at = value
}
type Observationable interface {
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.AdditionalDataHolder
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
    GetDurationMs()(*int64)
    GetEventType()(*string)
    GetEvidence()(*string)
    GetExperimentId()(*i561e97a8befe7661a44c8f54600992b4207a3a0cf6770e5559949bc276de2e22.UUID)
    GetId()(*i561e97a8befe7661a44c8f54600992b4207a3a0cf6770e5559949bc276de2e22.UUID)
    GetObservationKey()(*string)
    GetProfileId()(*string)
    GetSource()(*string)
    GetStartedAt()(*i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time)
    SetDurationMs(value *int64)()
    SetEventType(value *string)()
    SetEvidence(value *string)()
    SetExperimentId(value *i561e97a8befe7661a44c8f54600992b4207a3a0cf6770e5559949bc276de2e22.UUID)()
    SetId(value *i561e97a8befe7661a44c8f54600992b4207a3a0cf6770e5559949bc276de2e22.UUID)()
    SetObservationKey(value *string)()
    SetProfileId(value *string)()
    SetSource(value *string)()
    SetStartedAt(value *i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time)()
}
