// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package models

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

type PaginatedJobResponse struct {
    // Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
    additionalData map[string]any
    // The available_filters property
    available_filters PaginatedJobResponse_PaginatedJobResponse_available_filtersable
    // The jobs property
    jobs []JobResponseable
    // The total_count property
    total_count *int64
}
// PaginatedJobResponse_PaginatedJobResponse_available_filters composed type wrapper for classes AvailableFiltersable, PaginatedJobResponse_available_filtersMember1able
type PaginatedJobResponse_PaginatedJobResponse_available_filters struct {
    // Composed type representation for type AvailableFiltersable
    availableFilters AvailableFiltersable
    // Composed type representation for type PaginatedJobResponse_available_filtersMember1able
    paginatedJobResponse_available_filtersMember1 PaginatedJobResponse_available_filtersMember1able
}
// NewPaginatedJobResponse_PaginatedJobResponse_available_filters instantiates a new PaginatedJobResponse_PaginatedJobResponse_available_filters and sets the default values.
func NewPaginatedJobResponse_PaginatedJobResponse_available_filters()(*PaginatedJobResponse_PaginatedJobResponse_available_filters) {
    m := &PaginatedJobResponse_PaginatedJobResponse_available_filters{
    }
    return m
}
// CreatePaginatedJobResponse_PaginatedJobResponse_available_filtersFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreatePaginatedJobResponse_PaginatedJobResponse_available_filtersFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    result := NewPaginatedJobResponse_PaginatedJobResponse_available_filters()
    if parseNode != nil {
        mappingValueNode, err := parseNode.GetChildNode("")
        if err != nil {
            return nil, err
        }
        if mappingValueNode != nil {
            mappingValue, err := mappingValueNode.GetStringValue()
            if err != nil {
                return nil, err
            }
            if mappingValue != nil {
            }
        }
    }
    return result, nil
}
// GetAvailableFilters gets the AvailableFilters property value. Composed type representation for type AvailableFiltersable
// returns a AvailableFiltersable when successful
func (m *PaginatedJobResponse_PaginatedJobResponse_available_filters) GetAvailableFilters()(AvailableFiltersable) {
    return m.availableFilters
}
// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error) when successful
func (m *PaginatedJobResponse_PaginatedJobResponse_available_filters) GetFieldDeserializers()(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error)) {
    if m.GetAvailableFilters() != nil {
        return m.GetAvailableFilters().GetFieldDeserializers()
    } else if m.GetPaginatedJobResponseAvailableFiltersMember1() != nil {
        return m.GetPaginatedJobResponseAvailableFiltersMember1().GetFieldDeserializers()
    }
    return make(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error))
}
// GetIsComposedType determines if the current object is a wrapper around a composed type
// returns a bool when successful
func (m *PaginatedJobResponse_PaginatedJobResponse_available_filters) GetIsComposedType()(bool) {
    return true
}
// GetPaginatedJobResponseAvailableFiltersMember1 gets the PaginatedJobResponse_available_filtersMember1 property value. Composed type representation for type PaginatedJobResponse_available_filtersMember1able
// returns a PaginatedJobResponse_available_filtersMember1able when successful
func (m *PaginatedJobResponse_PaginatedJobResponse_available_filters) GetPaginatedJobResponseAvailableFiltersMember1()(PaginatedJobResponse_available_filtersMember1able) {
    return m.paginatedJobResponse_available_filtersMember1
}
// Serialize serializes information the current object
func (m *PaginatedJobResponse_PaginatedJobResponse_available_filters) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter)(error) {
    if m.GetAvailableFilters() != nil {
        err := writer.WriteObjectValue("", m.GetAvailableFilters())
        if err != nil {
            return err
        }
    } else if m.GetPaginatedJobResponseAvailableFiltersMember1() != nil {
        err := writer.WriteObjectValue("", m.GetPaginatedJobResponseAvailableFiltersMember1())
        if err != nil {
            return err
        }
    }
    return nil
}
// SetAvailableFilters sets the AvailableFilters property value. Composed type representation for type AvailableFiltersable
func (m *PaginatedJobResponse_PaginatedJobResponse_available_filters) SetAvailableFilters(value AvailableFiltersable)() {
    m.availableFilters = value
}
// SetPaginatedJobResponseAvailableFiltersMember1 sets the PaginatedJobResponse_available_filtersMember1 property value. Composed type representation for type PaginatedJobResponse_available_filtersMember1able
func (m *PaginatedJobResponse_PaginatedJobResponse_available_filters) SetPaginatedJobResponseAvailableFiltersMember1(value PaginatedJobResponse_available_filtersMember1able)() {
    m.paginatedJobResponse_available_filtersMember1 = value
}
type PaginatedJobResponse_PaginatedJobResponse_available_filtersable interface {
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
    GetAvailableFilters()(AvailableFiltersable)
    GetPaginatedJobResponseAvailableFiltersMember1()(PaginatedJobResponse_available_filtersMember1able)
    SetAvailableFilters(value AvailableFiltersable)()
    SetPaginatedJobResponseAvailableFiltersMember1(value PaginatedJobResponse_available_filtersMember1able)()
}
// NewPaginatedJobResponse instantiates a new PaginatedJobResponse and sets the default values.
func NewPaginatedJobResponse()(*PaginatedJobResponse) {
    m := &PaginatedJobResponse{
    }
    m.SetAdditionalData(make(map[string]any))
    return m
}
// CreatePaginatedJobResponseFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreatePaginatedJobResponseFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewPaginatedJobResponse(), nil
}
// GetAdditionalData gets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
// returns a map[string]any when successful
func (m *PaginatedJobResponse) GetAdditionalData()(map[string]any) {
    return m.additionalData
}
// GetAvailable_filters gets the available_filters property value. The available_filters property
// returns a PaginatedJobResponse_PaginatedJobResponse_available_filtersable when successful
func (m *PaginatedJobResponse) GetAvailable_filters()(PaginatedJobResponse_PaginatedJobResponse_available_filtersable) {
    return m.available_filters
}
// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error) when successful
func (m *PaginatedJobResponse) GetFieldDeserializers()(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error)) {
    res := make(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error))
    res["available_filters"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetObjectValue(CreatePaginatedJobResponse_PaginatedJobResponse_available_filtersFromDiscriminatorValue)
        if err != nil {
            return err
        }
        if val != nil {
            m.SetAvailable_filters(val.(PaginatedJobResponse_PaginatedJobResponse_available_filtersable))
        }
        return nil
    }
    res["jobs"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetCollectionOfObjectValues(CreateJobResponseFromDiscriminatorValue)
        if err != nil {
            return err
        }
        if val != nil {
            res := make([]JobResponseable, len(val))
            for i, v := range val {
                if v != nil {
                    res[i] = v.(JobResponseable)
                }
            }
            m.SetJobs(res)
        }
        return nil
    }
    res["total_count"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetInt64Value()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetTotalCount(val)
        }
        return nil
    }
    return res
}
// GetJobs gets the jobs property value. The jobs property
// returns a []JobResponseable when successful
func (m *PaginatedJobResponse) GetJobs()([]JobResponseable) {
    return m.jobs
}
// GetTotalCount gets the total_count property value. The total_count property
// returns a *int64 when successful
func (m *PaginatedJobResponse) GetTotalCount()(*int64) {
    return m.total_count
}
// Serialize serializes information the current object
func (m *PaginatedJobResponse) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter)(error) {
    {
        err := writer.WriteObjectValue("available_filters", m.GetAvailable_filters())
        if err != nil {
            return err
        }
    }
    if m.GetJobs() != nil {
        cast := make([]i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, len(m.GetJobs()))
        for i, v := range m.GetJobs() {
            if v != nil {
                cast[i] = v.(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable)
            }
        }
        err := writer.WriteCollectionOfObjectValues("jobs", cast)
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteInt64Value("total_count", m.GetTotalCount())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteAdditionalData(m.GetAdditionalData())
        if err != nil {
            return err
        }
    }
    return nil
}
// SetAdditionalData sets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
func (m *PaginatedJobResponse) SetAdditionalData(value map[string]any)() {
    m.additionalData = value
}
// SetAvailable_filters sets the available_filters property value. The available_filters property
func (m *PaginatedJobResponse) SetAvailable_filters(value PaginatedJobResponse_PaginatedJobResponse_available_filtersable)() {
    m.available_filters = value
}
// SetJobs sets the jobs property value. The jobs property
func (m *PaginatedJobResponse) SetJobs(value []JobResponseable)() {
    m.jobs = value
}
// SetTotalCount sets the total_count property value. The total_count property
func (m *PaginatedJobResponse) SetTotalCount(value *int64)() {
    m.total_count = value
}
type PaginatedJobResponseable interface {
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.AdditionalDataHolder
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
    GetAvailable_filters()(PaginatedJobResponse_PaginatedJobResponse_available_filtersable)
    GetJobs()([]JobResponseable)
    GetTotalCount()(*int64)
    SetAvailable_filters(value PaginatedJobResponse_PaginatedJobResponse_available_filtersable)()
    SetJobs(value []JobResponseable)()
    SetTotalCount(value *int64)()
}
