// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package models

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// PodStartupTime startup time for a single worker pod.
type PodStartupTime struct {
    // Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
    additionalData map[string]any
    // Whether this pod was started via a Cedana restore (true) or cold-started (false)
    cedana_restore *bool
    // Pod name
    pod_name *string
    // Time from PodScheduled → Ready in milliseconds
    start_time_ms *int64
}
// NewPodStartupTime instantiates a new PodStartupTime and sets the default values.
func NewPodStartupTime()(*PodStartupTime) {
    m := &PodStartupTime{
    }
    m.SetAdditionalData(make(map[string]any))
    return m
}
// CreatePodStartupTimeFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreatePodStartupTimeFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewPodStartupTime(), nil
}
// GetAdditionalData gets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
// returns a map[string]any when successful
func (m *PodStartupTime) GetAdditionalData()(map[string]any) {
    return m.additionalData
}
// GetCedanaRestore gets the cedana_restore property value. Whether this pod was started via a Cedana restore (true) or cold-started (false)
// returns a *bool when successful
func (m *PodStartupTime) GetCedanaRestore()(*bool) {
    return m.cedana_restore
}
// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error) when successful
func (m *PodStartupTime) GetFieldDeserializers()(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error)) {
    res := make(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error))
    res["cedana_restore"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetBoolValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetCedanaRestore(val)
        }
        return nil
    }
    res["pod_name"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetPodName(val)
        }
        return nil
    }
    res["start_time_ms"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetInt64Value()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetStartTimeMs(val)
        }
        return nil
    }
    return res
}
// GetPodName gets the pod_name property value. Pod name
// returns a *string when successful
func (m *PodStartupTime) GetPodName()(*string) {
    return m.pod_name
}
// GetStartTimeMs gets the start_time_ms property value. Time from PodScheduled → Ready in milliseconds
// returns a *int64 when successful
func (m *PodStartupTime) GetStartTimeMs()(*int64) {
    return m.start_time_ms
}
// Serialize serializes information the current object
func (m *PodStartupTime) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter)(error) {
    {
        err := writer.WriteBoolValue("cedana_restore", m.GetCedanaRestore())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("pod_name", m.GetPodName())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteInt64Value("start_time_ms", m.GetStartTimeMs())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteAdditionalData(m.GetAdditionalData())
        if err != nil {
            return err
        }
    }
    return nil
}
// SetAdditionalData sets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
func (m *PodStartupTime) SetAdditionalData(value map[string]any)() {
    m.additionalData = value
}
// SetCedanaRestore sets the cedana_restore property value. Whether this pod was started via a Cedana restore (true) or cold-started (false)
func (m *PodStartupTime) SetCedanaRestore(value *bool)() {
    m.cedana_restore = value
}
// SetPodName sets the pod_name property value. Pod name
func (m *PodStartupTime) SetPodName(value *string)() {
    m.pod_name = value
}
// SetStartTimeMs sets the start_time_ms property value. Time from PodScheduled → Ready in milliseconds
func (m *PodStartupTime) SetStartTimeMs(value *int64)() {
    m.start_time_ms = value
}
type PodStartupTimeable interface {
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.AdditionalDataHolder
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
    GetCedanaRestore()(*bool)
    GetPodName()(*string)
    GetStartTimeMs()(*int64)
    SetCedanaRestore(value *bool)()
    SetPodName(value *string)()
    SetStartTimeMs(value *int64)()
}
