// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package models

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

type RestorePod struct {
    // The action_id property
    action_id *string
    // Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
    additionalData map[string]any
    // The cluster_id property
    cluster_id *string
    // The overrides property
    overrides RestorePod_RestorePod_overridesable
    // The reason property
    reason *RestoreReason
}
// RestorePod_RestorePod_overrides composed type wrapper for classes RestoreOverridesable, RestorePod_overridesMember1able
type RestorePod_RestorePod_overrides struct {
    // Composed type representation for type RestoreOverridesable
    restoreOverrides RestoreOverridesable
    // Composed type representation for type RestorePod_overridesMember1able
    restorePod_overridesMember1 RestorePod_overridesMember1able
}
// NewRestorePod_RestorePod_overrides instantiates a new RestorePod_RestorePod_overrides and sets the default values.
func NewRestorePod_RestorePod_overrides()(*RestorePod_RestorePod_overrides) {
    m := &RestorePod_RestorePod_overrides{
    }
    return m
}
// CreateRestorePod_RestorePod_overridesFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateRestorePod_RestorePod_overridesFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    result := NewRestorePod_RestorePod_overrides()
    if parseNode != nil {
        mappingValueNode, err := parseNode.GetChildNode("")
        if err != nil {
            return nil, err
        }
        if mappingValueNode != nil {
            mappingValue, err := mappingValueNode.GetStringValue()
            if err != nil {
                return nil, err
            }
            if mappingValue != nil {
            }
        }
    }
    return result, nil
}
// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error) when successful
func (m *RestorePod_RestorePod_overrides) GetFieldDeserializers()(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error)) {
    if m.GetRestoreOverrides() != nil {
        return m.GetRestoreOverrides().GetFieldDeserializers()
    } else if m.GetRestorePodOverridesMember1() != nil {
        return m.GetRestorePodOverridesMember1().GetFieldDeserializers()
    }
    return make(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error))
}
// GetIsComposedType determines if the current object is a wrapper around a composed type
// returns a bool when successful
func (m *RestorePod_RestorePod_overrides) GetIsComposedType()(bool) {
    return true
}
// GetRestoreOverrides gets the RestoreOverrides property value. Composed type representation for type RestoreOverridesable
// returns a RestoreOverridesable when successful
func (m *RestorePod_RestorePod_overrides) GetRestoreOverrides()(RestoreOverridesable) {
    return m.restoreOverrides
}
// GetRestorePodOverridesMember1 gets the RestorePod_overridesMember1 property value. Composed type representation for type RestorePod_overridesMember1able
// returns a RestorePod_overridesMember1able when successful
func (m *RestorePod_RestorePod_overrides) GetRestorePodOverridesMember1()(RestorePod_overridesMember1able) {
    return m.restorePod_overridesMember1
}
// Serialize serializes information the current object
func (m *RestorePod_RestorePod_overrides) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter)(error) {
    if m.GetRestoreOverrides() != nil {
        err := writer.WriteObjectValue("", m.GetRestoreOverrides())
        if err != nil {
            return err
        }
    } else if m.GetRestorePodOverridesMember1() != nil {
        err := writer.WriteObjectValue("", m.GetRestorePodOverridesMember1())
        if err != nil {
            return err
        }
    }
    return nil
}
// SetRestoreOverrides sets the RestoreOverrides property value. Composed type representation for type RestoreOverridesable
func (m *RestorePod_RestorePod_overrides) SetRestoreOverrides(value RestoreOverridesable)() {
    m.restoreOverrides = value
}
// SetRestorePodOverridesMember1 sets the RestorePod_overridesMember1 property value. Composed type representation for type RestorePod_overridesMember1able
func (m *RestorePod_RestorePod_overrides) SetRestorePodOverridesMember1(value RestorePod_overridesMember1able)() {
    m.restorePod_overridesMember1 = value
}
type RestorePod_RestorePod_overridesable interface {
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
    GetRestoreOverrides()(RestoreOverridesable)
    GetRestorePodOverridesMember1()(RestorePod_overridesMember1able)
    SetRestoreOverrides(value RestoreOverridesable)()
    SetRestorePodOverridesMember1(value RestorePod_overridesMember1able)()
}
// NewRestorePod instantiates a new RestorePod and sets the default values.
func NewRestorePod()(*RestorePod) {
    m := &RestorePod{
    }
    m.SetAdditionalData(make(map[string]any))
    return m
}
// CreateRestorePodFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateRestorePodFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewRestorePod(), nil
}
// GetActionId gets the action_id property value. The action_id property
// returns a *string when successful
func (m *RestorePod) GetActionId()(*string) {
    return m.action_id
}
// GetAdditionalData gets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
// returns a map[string]any when successful
func (m *RestorePod) GetAdditionalData()(map[string]any) {
    return m.additionalData
}
// GetClusterId gets the cluster_id property value. The cluster_id property
// returns a *string when successful
func (m *RestorePod) GetClusterId()(*string) {
    return m.cluster_id
}
// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error) when successful
func (m *RestorePod) GetFieldDeserializers()(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error)) {
    res := make(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error))
    res["action_id"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetActionId(val)
        }
        return nil
    }
    res["cluster_id"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetClusterId(val)
        }
        return nil
    }
    res["overrides"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetObjectValue(CreateRestorePod_RestorePod_overridesFromDiscriminatorValue)
        if err != nil {
            return err
        }
        if val != nil {
            m.SetOverrides(val.(RestorePod_RestorePod_overridesable))
        }
        return nil
    }
    res["reason"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetEnumValue(ParseRestoreReason)
        if err != nil {
            return err
        }
        if val != nil {
            m.SetReason(val.(*RestoreReason))
        }
        return nil
    }
    return res
}
// GetOverrides gets the overrides property value. The overrides property
// returns a RestorePod_RestorePod_overridesable when successful
func (m *RestorePod) GetOverrides()(RestorePod_RestorePod_overridesable) {
    return m.overrides
}
// GetReason gets the reason property value. The reason property
// returns a *RestoreReason when successful
func (m *RestorePod) GetReason()(*RestoreReason) {
    return m.reason
}
// Serialize serializes information the current object
func (m *RestorePod) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter)(error) {
    {
        err := writer.WriteStringValue("action_id", m.GetActionId())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("cluster_id", m.GetClusterId())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteObjectValue("overrides", m.GetOverrides())
        if err != nil {
            return err
        }
    }
    if m.GetReason() != nil {
        cast := (*m.GetReason()).String()
        err := writer.WriteStringValue("reason", &cast)
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteAdditionalData(m.GetAdditionalData())
        if err != nil {
            return err
        }
    }
    return nil
}
// SetActionId sets the action_id property value. The action_id property
func (m *RestorePod) SetActionId(value *string)() {
    m.action_id = value
}
// SetAdditionalData sets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
func (m *RestorePod) SetAdditionalData(value map[string]any)() {
    m.additionalData = value
}
// SetClusterId sets the cluster_id property value. The cluster_id property
func (m *RestorePod) SetClusterId(value *string)() {
    m.cluster_id = value
}
// SetOverrides sets the overrides property value. The overrides property
func (m *RestorePod) SetOverrides(value RestorePod_RestorePod_overridesable)() {
    m.overrides = value
}
// SetReason sets the reason property value. The reason property
func (m *RestorePod) SetReason(value *RestoreReason)() {
    m.reason = value
}
type RestorePodable interface {
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.AdditionalDataHolder
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
    GetActionId()(*string)
    GetClusterId()(*string)
    GetOverrides()(RestorePod_RestorePod_overridesable)
    GetReason()(*RestoreReason)
    SetActionId(value *string)()
    SetClusterId(value *string)()
    SetOverrides(value RestorePod_RestorePod_overridesable)()
    SetReason(value *RestoreReason)()
}
