// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package models

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

type SlurmJob struct {
    // Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
    additionalData map[string]any
    // The job_id property
    job_id *string
    // The job_name property
    job_name *string
    // The priority property
    priority *int32
    // The state property
    state *string
}
// NewSlurmJob instantiates a new SlurmJob and sets the default values.
func NewSlurmJob()(*SlurmJob) {
    m := &SlurmJob{
    }
    m.SetAdditionalData(make(map[string]any))
    return m
}
// CreateSlurmJobFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateSlurmJobFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewSlurmJob(), nil
}
// GetAdditionalData gets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
// returns a map[string]any when successful
func (m *SlurmJob) GetAdditionalData()(map[string]any) {
    return m.additionalData
}
// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error) when successful
func (m *SlurmJob) GetFieldDeserializers()(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error)) {
    res := make(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error))
    res["job_id"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetJobId(val)
        }
        return nil
    }
    res["job_name"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetJobName(val)
        }
        return nil
    }
    res["priority"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetInt32Value()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetPriority(val)
        }
        return nil
    }
    res["state"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetState(val)
        }
        return nil
    }
    return res
}
// GetJobId gets the job_id property value. The job_id property
// returns a *string when successful
func (m *SlurmJob) GetJobId()(*string) {
    return m.job_id
}
// GetJobName gets the job_name property value. The job_name property
// returns a *string when successful
func (m *SlurmJob) GetJobName()(*string) {
    return m.job_name
}
// GetPriority gets the priority property value. The priority property
// returns a *int32 when successful
func (m *SlurmJob) GetPriority()(*int32) {
    return m.priority
}
// GetState gets the state property value. The state property
// returns a *string when successful
func (m *SlurmJob) GetState()(*string) {
    return m.state
}
// Serialize serializes information the current object
func (m *SlurmJob) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter)(error) {
    {
        err := writer.WriteStringValue("job_id", m.GetJobId())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("job_name", m.GetJobName())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteInt32Value("priority", m.GetPriority())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("state", m.GetState())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteAdditionalData(m.GetAdditionalData())
        if err != nil {
            return err
        }
    }
    return nil
}
// SetAdditionalData sets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
func (m *SlurmJob) SetAdditionalData(value map[string]any)() {
    m.additionalData = value
}
// SetJobId sets the job_id property value. The job_id property
func (m *SlurmJob) SetJobId(value *string)() {
    m.job_id = value
}
// SetJobName sets the job_name property value. The job_name property
func (m *SlurmJob) SetJobName(value *string)() {
    m.job_name = value
}
// SetPriority sets the priority property value. The priority property
func (m *SlurmJob) SetPriority(value *int32)() {
    m.priority = value
}
// SetState sets the state property value. The state property
func (m *SlurmJob) SetState(value *string)() {
    m.state = value
}
type SlurmJobable interface {
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.AdditionalDataHolder
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
    GetJobId()(*string)
    GetJobName()(*string)
    GetPriority()(*int32)
    GetState()(*string)
    SetJobId(value *string)()
    SetJobName(value *string)()
    SetPriority(value *int32)()
    SetState(value *string)()
}
