// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package models

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

type StorageAnalytics struct {
    // Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
    additionalData map[string]any
    // The dedup_ratio property
    dedup_ratio *float64
    // The incremental_ratio property
    incremental_ratio *float64
    // The logical_bytes property
    logical_bytes *int64
    // The physical_bytes property
    physical_bytes *int64
    // The reused_bytes property
    reused_bytes *int64
    // The transferred_bytes property
    transferred_bytes *int64
    // The written_bytes property
    written_bytes *int64
}
// NewStorageAnalytics instantiates a new StorageAnalytics and sets the default values.
func NewStorageAnalytics()(*StorageAnalytics) {
    m := &StorageAnalytics{
    }
    m.SetAdditionalData(make(map[string]any))
    return m
}
// CreateStorageAnalyticsFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateStorageAnalyticsFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewStorageAnalytics(), nil
}
// GetAdditionalData gets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
// returns a map[string]any when successful
func (m *StorageAnalytics) GetAdditionalData()(map[string]any) {
    return m.additionalData
}
// GetDedupRatio gets the dedup_ratio property value. The dedup_ratio property
// returns a *float64 when successful
func (m *StorageAnalytics) GetDedupRatio()(*float64) {
    return m.dedup_ratio
}
// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error) when successful
func (m *StorageAnalytics) GetFieldDeserializers()(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error)) {
    res := make(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error))
    res["dedup_ratio"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetFloat64Value()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetDedupRatio(val)
        }
        return nil
    }
    res["incremental_ratio"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetFloat64Value()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetIncrementalRatio(val)
        }
        return nil
    }
    res["logical_bytes"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetInt64Value()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetLogicalBytes(val)
        }
        return nil
    }
    res["physical_bytes"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetInt64Value()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetPhysicalBytes(val)
        }
        return nil
    }
    res["reused_bytes"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetInt64Value()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetReusedBytes(val)
        }
        return nil
    }
    res["transferred_bytes"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetInt64Value()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetTransferredBytes(val)
        }
        return nil
    }
    res["written_bytes"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetInt64Value()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetWrittenBytes(val)
        }
        return nil
    }
    return res
}
// GetIncrementalRatio gets the incremental_ratio property value. The incremental_ratio property
// returns a *float64 when successful
func (m *StorageAnalytics) GetIncrementalRatio()(*float64) {
    return m.incremental_ratio
}
// GetLogicalBytes gets the logical_bytes property value. The logical_bytes property
// returns a *int64 when successful
func (m *StorageAnalytics) GetLogicalBytes()(*int64) {
    return m.logical_bytes
}
// GetPhysicalBytes gets the physical_bytes property value. The physical_bytes property
// returns a *int64 when successful
func (m *StorageAnalytics) GetPhysicalBytes()(*int64) {
    return m.physical_bytes
}
// GetReusedBytes gets the reused_bytes property value. The reused_bytes property
// returns a *int64 when successful
func (m *StorageAnalytics) GetReusedBytes()(*int64) {
    return m.reused_bytes
}
// GetTransferredBytes gets the transferred_bytes property value. The transferred_bytes property
// returns a *int64 when successful
func (m *StorageAnalytics) GetTransferredBytes()(*int64) {
    return m.transferred_bytes
}
// GetWrittenBytes gets the written_bytes property value. The written_bytes property
// returns a *int64 when successful
func (m *StorageAnalytics) GetWrittenBytes()(*int64) {
    return m.written_bytes
}
// Serialize serializes information the current object
func (m *StorageAnalytics) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter)(error) {
    {
        err := writer.WriteFloat64Value("dedup_ratio", m.GetDedupRatio())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteFloat64Value("incremental_ratio", m.GetIncrementalRatio())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteInt64Value("logical_bytes", m.GetLogicalBytes())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteInt64Value("physical_bytes", m.GetPhysicalBytes())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteInt64Value("reused_bytes", m.GetReusedBytes())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteInt64Value("transferred_bytes", m.GetTransferredBytes())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteInt64Value("written_bytes", m.GetWrittenBytes())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteAdditionalData(m.GetAdditionalData())
        if err != nil {
            return err
        }
    }
    return nil
}
// SetAdditionalData sets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
func (m *StorageAnalytics) SetAdditionalData(value map[string]any)() {
    m.additionalData = value
}
// SetDedupRatio sets the dedup_ratio property value. The dedup_ratio property
func (m *StorageAnalytics) SetDedupRatio(value *float64)() {
    m.dedup_ratio = value
}
// SetIncrementalRatio sets the incremental_ratio property value. The incremental_ratio property
func (m *StorageAnalytics) SetIncrementalRatio(value *float64)() {
    m.incremental_ratio = value
}
// SetLogicalBytes sets the logical_bytes property value. The logical_bytes property
func (m *StorageAnalytics) SetLogicalBytes(value *int64)() {
    m.logical_bytes = value
}
// SetPhysicalBytes sets the physical_bytes property value. The physical_bytes property
func (m *StorageAnalytics) SetPhysicalBytes(value *int64)() {
    m.physical_bytes = value
}
// SetReusedBytes sets the reused_bytes property value. The reused_bytes property
func (m *StorageAnalytics) SetReusedBytes(value *int64)() {
    m.reused_bytes = value
}
// SetTransferredBytes sets the transferred_bytes property value. The transferred_bytes property
func (m *StorageAnalytics) SetTransferredBytes(value *int64)() {
    m.transferred_bytes = value
}
// SetWrittenBytes sets the written_bytes property value. The written_bytes property
func (m *StorageAnalytics) SetWrittenBytes(value *int64)() {
    m.written_bytes = value
}
type StorageAnalyticsable interface {
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.AdditionalDataHolder
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
    GetDedupRatio()(*float64)
    GetIncrementalRatio()(*float64)
    GetLogicalBytes()(*int64)
    GetPhysicalBytes()(*int64)
    GetReusedBytes()(*int64)
    GetTransferredBytes()(*int64)
    GetWrittenBytes()(*int64)
    SetDedupRatio(value *float64)()
    SetIncrementalRatio(value *float64)()
    SetLogicalBytes(value *int64)()
    SetPhysicalBytes(value *int64)()
    SetReusedBytes(value *int64)()
    SetTransferredBytes(value *int64)()
    SetWrittenBytes(value *int64)()
}
