// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package models

import (
    i561e97a8befe7661a44c8f54600992b4207a3a0cf6770e5559949bc276de2e22 "github.com/google/uuid"
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// UpdateCheckpointRequest what the controller reports back about a request it picked up.
type UpdateCheckpointRequest struct {
    // Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
    additionalData map[string]any
    // The artifact_id property
    artifact_id *string
    // The error property
    error *string
    // Correlates this report to the request it describes, so a late report from asuperseded attempt cannot overwrite the current outcome.
    request_id *i561e97a8befe7661a44c8f54600992b4207a3a0cf6770e5559949bc276de2e22.UUID
    // running when the dump starts, then succeeded or failed.
    status *string
}
// NewUpdateCheckpointRequest instantiates a new UpdateCheckpointRequest and sets the default values.
func NewUpdateCheckpointRequest()(*UpdateCheckpointRequest) {
    m := &UpdateCheckpointRequest{
    }
    m.SetAdditionalData(make(map[string]any))
    return m
}
// CreateUpdateCheckpointRequestFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateUpdateCheckpointRequestFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewUpdateCheckpointRequest(), nil
}
// GetAdditionalData gets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
// returns a map[string]any when successful
func (m *UpdateCheckpointRequest) GetAdditionalData()(map[string]any) {
    return m.additionalData
}
// GetArtifactId gets the artifact_id property value. The artifact_id property
// returns a *string when successful
func (m *UpdateCheckpointRequest) GetArtifactId()(*string) {
    return m.artifact_id
}
// GetError gets the error property value. The error property
// returns a *string when successful
func (m *UpdateCheckpointRequest) GetError()(*string) {
    return m.error
}
// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error) when successful
func (m *UpdateCheckpointRequest) GetFieldDeserializers()(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error)) {
    res := make(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error))
    res["artifact_id"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetArtifactId(val)
        }
        return nil
    }
    res["error"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetError(val)
        }
        return nil
    }
    res["request_id"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetUUIDValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetRequestId(val)
        }
        return nil
    }
    res["status"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetStatus(val)
        }
        return nil
    }
    return res
}
// GetRequestId gets the request_id property value. Correlates this report to the request it describes, so a late report from asuperseded attempt cannot overwrite the current outcome.
// returns a *UUID when successful
func (m *UpdateCheckpointRequest) GetRequestId()(*i561e97a8befe7661a44c8f54600992b4207a3a0cf6770e5559949bc276de2e22.UUID) {
    return m.request_id
}
// GetStatus gets the status property value. running when the dump starts, then succeeded or failed.
// returns a *string when successful
func (m *UpdateCheckpointRequest) GetStatus()(*string) {
    return m.status
}
// Serialize serializes information the current object
func (m *UpdateCheckpointRequest) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter)(error) {
    {
        err := writer.WriteStringValue("artifact_id", m.GetArtifactId())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("error", m.GetError())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteUUIDValue("request_id", m.GetRequestId())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("status", m.GetStatus())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteAdditionalData(m.GetAdditionalData())
        if err != nil {
            return err
        }
    }
    return nil
}
// SetAdditionalData sets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
func (m *UpdateCheckpointRequest) SetAdditionalData(value map[string]any)() {
    m.additionalData = value
}
// SetArtifactId sets the artifact_id property value. The artifact_id property
func (m *UpdateCheckpointRequest) SetArtifactId(value *string)() {
    m.artifact_id = value
}
// SetError sets the error property value. The error property
func (m *UpdateCheckpointRequest) SetError(value *string)() {
    m.error = value
}
// SetRequestId sets the request_id property value. Correlates this report to the request it describes, so a late report from asuperseded attempt cannot overwrite the current outcome.
func (m *UpdateCheckpointRequest) SetRequestId(value *i561e97a8befe7661a44c8f54600992b4207a3a0cf6770e5559949bc276de2e22.UUID)() {
    m.request_id = value
}
// SetStatus sets the status property value. running when the dump starts, then succeeded or failed.
func (m *UpdateCheckpointRequest) SetStatus(value *string)() {
    m.status = value
}
type UpdateCheckpointRequestable interface {
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.AdditionalDataHolder
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
    GetArtifactId()(*string)
    GetError()(*string)
    GetRequestId()(*i561e97a8befe7661a44c8f54600992b4207a3a0cf6770e5559949bc276de2e22.UUID)
    GetStatus()(*string)
    SetArtifactId(value *string)()
    SetError(value *string)()
    SetRequestId(value *i561e97a8befe7661a44c8f54600992b4207a3a0cf6770e5559949bc276de2e22.UUID)()
    SetStatus(value *string)()
}
